/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;

/**
 *
 * @author User
 */
public class FormInicioAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FormInicioAdministrador
     */
    int xMouse,yMouse;    
    public FormInicioAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        pnlRegresar = new javax.swing.JPanel();
        txtRegresar = new javax.swing.JLabel();
        imagenAlumno = new javax.swing.JLabel();
        pnlEliminarAlumno = new javax.swing.JPanel();
        btnEliminarAlumno = new javax.swing.JLabel();
        txtEliminarAlumno = new javax.swing.JLabel();
        txtAgregarAlumno = new javax.swing.JLabel();
        pnlAgregarAlumno = new javax.swing.JPanel();
        btnAgregarAlumno = new javax.swing.JLabel();
        pnlBuscarAlumno = new javax.swing.JPanel();
        btnBuscarAlumno = new javax.swing.JLabel();
        pnlActualizarAlumno = new javax.swing.JPanel();
        btnActualizarAlumno = new javax.swing.JLabel();
        pnlListarAlumno = new javax.swing.JPanel();
        btnListarAlumno = new javax.swing.JLabel();
        txtBuscarAlumno = new javax.swing.JLabel();
        txtActualizarAlumno = new javax.swing.JLabel();
        txtListarAlumno = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        imagenProfesor = new javax.swing.JLabel();
        pnlEliminarProfesor = new javax.swing.JPanel();
        btnEliminarProfesor = new javax.swing.JLabel();
        txtEliminarProfesor = new javax.swing.JLabel();
        txtAgregarProfesor = new javax.swing.JLabel();
        pnlAgregarProfesor = new javax.swing.JPanel();
        btnAgregarProfesor = new javax.swing.JLabel();
        pnlBuscarProfesor = new javax.swing.JPanel();
        btnBuscarProfesor = new javax.swing.JLabel();
        pnlActualizarProfesor = new javax.swing.JPanel();
        btnActualizarProfesor = new javax.swing.JLabel();
        pnlListarProfesor = new javax.swing.JPanel();
        btnListarProfesor = new javax.swing.JLabel();
        txtBuscarProfesor = new javax.swing.JLabel();
        txtActualizarProfesor = new javax.swing.JLabel();
        txtListarProfesor = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        imagenProfesor1 = new javax.swing.JLabel();
        pnlEliminarMatricula = new javax.swing.JPanel();
        btnEliminarMatricula = new javax.swing.JLabel();
        txtEliminarMatricula = new javax.swing.JLabel();
        txtAgregarMatricula = new javax.swing.JLabel();
        pnlAgregarMatricula = new javax.swing.JPanel();
        btnAgregarMatricula = new javax.swing.JLabel();
        pnlBuscarMatricula = new javax.swing.JPanel();
        btnBuscarMatricula = new javax.swing.JLabel();
        pnlActualizarMatricula = new javax.swing.JPanel();
        btnActualizarMatricula = new javax.swing.JLabel();
        pnlListarMatricula = new javax.swing.JPanel();
        btnListarMatricula = new javax.swing.JLabel();
        txtBuscarMatricula = new javax.swing.JLabel();
        txtActualizarMatricula = new javax.swing.JLabel();
        txtListarMatricula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlRegresar.setBackground(new java.awt.Color(255, 255, 255));

        txtRegresar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegresar.setText("<-");
        txtRegresar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRegresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlRegresarLayout = new javax.swing.GroupLayout(pnlRegresar);
        pnlRegresar.setLayout(pnlRegresarLayout);
        pnlRegresarLayout.setHorizontalGroup(
            pnlRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRegresarLayout.setVerticalGroup(
            pnlRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(pnlRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1000, Short.MAX_VALUE)
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        imagenAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioImagen1.jpg"))); // NOI18N
        jPanel1.add(imagenAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, 170));

        pnlEliminarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnEliminarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnEliminarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarAlumno.setText("ELIMINAR");
        btnEliminarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarAlumnoLayout = new javax.swing.GroupLayout(pnlEliminarAlumno);
        pnlEliminarAlumno.setLayout(pnlEliminarAlumnoLayout);
        pnlEliminarAlumnoLayout.setHorizontalGroup(
            pnlEliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlEliminarAlumnoLayout.setVerticalGroup(
            pnlEliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, 150, 40));

        txtEliminarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtEliminarAlumno.setText("Eliminar Alumno");
        jPanel1.add(txtEliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, -1));

        txtAgregarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtAgregarAlumno.setText("Agregar Alumno");
        jPanel1.add(txtAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        pnlAgregarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnAgregarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnAgregarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarAlumno.setText("AGREGAR");
        btnAgregarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarAlumnoLayout = new javax.swing.GroupLayout(pnlAgregarAlumno);
        pnlAgregarAlumno.setLayout(pnlAgregarAlumnoLayout);
        pnlAgregarAlumnoLayout.setHorizontalGroup(
            pnlAgregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlAgregarAlumnoLayout.setVerticalGroup(
            pnlAgregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarAlumnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 150, 40));

        pnlBuscarAlumno.setBackground(new java.awt.Color(254, 199, 7));
        pnlBuscarAlumno.setToolTipText("");

        btnBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnBuscarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAlumnoLayout = new javax.swing.GroupLayout(pnlBuscarAlumno);
        pnlBuscarAlumno.setLayout(pnlBuscarAlumnoLayout);
        pnlBuscarAlumnoLayout.setHorizontalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlBuscarAlumnoLayout.setVerticalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 150, 40));

        pnlActualizarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnActualizarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnActualizarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarAlumno.setText("ACTUALIZAR");
        btnActualizarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarAlumnoLayout = new javax.swing.GroupLayout(pnlActualizarAlumno);
        pnlActualizarAlumno.setLayout(pnlActualizarAlumnoLayout);
        pnlActualizarAlumnoLayout.setHorizontalGroup(
            pnlActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlActualizarAlumnoLayout.setVerticalGroup(
            pnlActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 150, 40));

        pnlListarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnListarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnListarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListarAlumno.setText("LISTAR");
        btnListarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlListarAlumnoLayout = new javax.swing.GroupLayout(pnlListarAlumno);
        pnlListarAlumno.setLayout(pnlListarAlumnoLayout);
        pnlListarAlumnoLayout.setHorizontalGroup(
            pnlListarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlListarAlumnoLayout.setVerticalGroup(
            pnlListarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlListarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 150, 40));

        txtBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtBuscarAlumno.setText("Buscar Alumno");
        jPanel1.add(txtBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        txtActualizarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtActualizarAlumno.setText("Actualizar Alumno");
        jPanel1.add(txtActualizarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        txtListarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtListarAlumno.setText("Listar Alumno");
        jPanel1.add(txtListarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jPanel7.setBackground(new java.awt.Color(254, 199, 7));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 3, 690));

        imagenProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioImagen2.jpg"))); // NOI18N
        jPanel1.add(imagenProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 170, 170));

        pnlEliminarProfesor.setBackground(new java.awt.Color(254, 199, 7));

        btnEliminarProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnEliminarProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarProfesor.setText("ELIMINAR");
        btnEliminarProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarProfesorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarProfesorLayout = new javax.swing.GroupLayout(pnlEliminarProfesor);
        pnlEliminarProfesor.setLayout(pnlEliminarProfesorLayout);
        pnlEliminarProfesorLayout.setHorizontalGroup(
            pnlEliminarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlEliminarProfesorLayout.setVerticalGroup(
            pnlEliminarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEliminarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 150, 40));

        txtEliminarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtEliminarProfesor.setText("Eliminar Alumno");
        jPanel1.add(txtEliminarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, -1, -1));

        txtAgregarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtAgregarProfesor.setText("Agregar Profesor");
        jPanel1.add(txtAgregarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        pnlAgregarProfesor.setBackground(new java.awt.Color(254, 199, 7));

        btnAgregarProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnAgregarProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarProfesor.setText("AGREGAR");
        btnAgregarProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProfesorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarProfesorLayout = new javax.swing.GroupLayout(pnlAgregarProfesor);
        pnlAgregarProfesor.setLayout(pnlAgregarProfesorLayout);
        pnlAgregarProfesorLayout.setHorizontalGroup(
            pnlAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlAgregarProfesorLayout.setVerticalGroup(
            pnlAgregarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarProfesorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlAgregarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 150, 40));

        pnlBuscarProfesor.setBackground(new java.awt.Color(254, 199, 7));
        pnlBuscarProfesor.setToolTipText("");

        btnBuscarProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnBuscarProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarProfesor.setText("BUSCAR");
        btnBuscarProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarProfesorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarProfesorLayout = new javax.swing.GroupLayout(pnlBuscarProfesor);
        pnlBuscarProfesor.setLayout(pnlBuscarProfesorLayout);
        pnlBuscarProfesorLayout.setHorizontalGroup(
            pnlBuscarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlBuscarProfesorLayout.setVerticalGroup(
            pnlBuscarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 150, 40));

        pnlActualizarProfesor.setBackground(new java.awt.Color(254, 199, 7));

        btnActualizarProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnActualizarProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarProfesor.setText("ACTUALIZAR");
        btnActualizarProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarProfesorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarProfesorLayout = new javax.swing.GroupLayout(pnlActualizarProfesor);
        pnlActualizarProfesor.setLayout(pnlActualizarProfesorLayout);
        pnlActualizarProfesorLayout.setHorizontalGroup(
            pnlActualizarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlActualizarProfesorLayout.setVerticalGroup(
            pnlActualizarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 150, 40));

        pnlListarProfesor.setBackground(new java.awt.Color(254, 199, 7));

        btnListarProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnListarProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListarProfesor.setText("LISTAR");
        btnListarProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarProfesorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlListarProfesorLayout = new javax.swing.GroupLayout(pnlListarProfesor);
        pnlListarProfesor.setLayout(pnlListarProfesorLayout);
        pnlListarProfesorLayout.setHorizontalGroup(
            pnlListarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlListarProfesorLayout.setVerticalGroup(
            pnlListarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlListarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 150, 40));

        txtBuscarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtBuscarProfesor.setText("Buscar Profesor");
        jPanel1.add(txtBuscarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        txtActualizarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtActualizarProfesor.setText("Actualizar Profesor");
        jPanel1.add(txtActualizarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        txtListarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtListarProfesor.setText("Listar Profesor");
        jPanel1.add(txtListarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jPanel8.setBackground(new java.awt.Color(254, 199, 7));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 3, 690));

        imagenProfesor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioImagen3.jpg"))); // NOI18N
        jPanel1.add(imagenProfesor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 150, 150));

        pnlEliminarMatricula.setBackground(new java.awt.Color(254, 199, 7));

        btnEliminarMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnEliminarMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarMatricula.setText("ELIMINAR");
        btnEliminarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarMatriculaLayout = new javax.swing.GroupLayout(pnlEliminarMatricula);
        pnlEliminarMatricula.setLayout(pnlEliminarMatriculaLayout);
        pnlEliminarMatriculaLayout.setHorizontalGroup(
            pnlEliminarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlEliminarMatriculaLayout.setVerticalGroup(
            pnlEliminarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEliminarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 150, 40));

        txtEliminarMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtEliminarMatricula.setText("Eliminar Matricula");
        jPanel1.add(txtEliminarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, -1, -1));

        txtAgregarMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtAgregarMatricula.setText("Agregar Matricula");
        jPanel1.add(txtAgregarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        pnlAgregarMatricula.setBackground(new java.awt.Color(254, 199, 7));

        btnAgregarMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnAgregarMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarMatricula.setText("AGREGAR");
        btnAgregarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarMatriculaLayout = new javax.swing.GroupLayout(pnlAgregarMatricula);
        pnlAgregarMatricula.setLayout(pnlAgregarMatriculaLayout);
        pnlAgregarMatriculaLayout.setHorizontalGroup(
            pnlAgregarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlAgregarMatriculaLayout.setVerticalGroup(
            pnlAgregarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarMatriculaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlAgregarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 150, 40));

        pnlBuscarMatricula.setBackground(new java.awt.Color(254, 199, 7));
        pnlBuscarMatricula.setToolTipText("");

        btnBuscarMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnBuscarMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarMatricula.setText("BUSCAR");
        btnBuscarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarMatriculaLayout = new javax.swing.GroupLayout(pnlBuscarMatricula);
        pnlBuscarMatricula.setLayout(pnlBuscarMatriculaLayout);
        pnlBuscarMatriculaLayout.setHorizontalGroup(
            pnlBuscarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlBuscarMatriculaLayout.setVerticalGroup(
            pnlBuscarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 150, 40));

        pnlActualizarMatricula.setBackground(new java.awt.Color(254, 199, 7));

        btnActualizarMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnActualizarMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarMatricula.setText("ACTUALIZAR");
        btnActualizarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarMatriculaLayout = new javax.swing.GroupLayout(pnlActualizarMatricula);
        pnlActualizarMatricula.setLayout(pnlActualizarMatriculaLayout);
        pnlActualizarMatriculaLayout.setHorizontalGroup(
            pnlActualizarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlActualizarMatriculaLayout.setVerticalGroup(
            pnlActualizarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 150, 40));

        pnlListarMatricula.setBackground(new java.awt.Color(254, 199, 7));

        btnListarMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnListarMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListarMatricula.setText("LISTAR");
        btnListarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlListarMatriculaLayout = new javax.swing.GroupLayout(pnlListarMatricula);
        pnlListarMatricula.setLayout(pnlListarMatriculaLayout);
        pnlListarMatriculaLayout.setHorizontalGroup(
            pnlListarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlListarMatriculaLayout.setVerticalGroup(
            pnlListarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlListarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 150, 40));

        txtBuscarMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtBuscarMatricula.setText("Buscar Matricula");
        jPanel1.add(txtBuscarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        txtActualizarMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtActualizarMatricula.setText("Actualizar Matricula");
        jPanel1.add(txtActualizarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        txtListarMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtListarMatricula.setText("Listar Matricula");
        jPanel1.add(txtListarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPredeAlumno.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnAgregarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoMouseClicked
        FormAgregarAlumno agregar = new FormAgregarAlumno();
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarAlumnoMouseClicked

    private void btnAgregarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoMouseEntered
        pnlAgregarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnAgregarAlumnoMouseEntered

    private void btnBuscarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseEntered
        pnlBuscarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarAlumnoMouseEntered

    private void btnActualizarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseEntered
        pnlActualizarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarAlumnoMouseEntered

    private void btnListarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarAlumnoMouseEntered
        pnlListarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnListarAlumnoMouseEntered

    private void btnEliminarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoMouseEntered
        pnlEliminarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnEliminarAlumnoMouseEntered

    private void btnAgregarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoMouseExited
        pnlAgregarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnAgregarAlumnoMouseExited

    private void btnBuscarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseExited
        pnlBuscarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarAlumnoMouseExited

    private void btnActualizarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseExited
        pnlActualizarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarAlumnoMouseExited

    private void btnListarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarAlumnoMouseExited
        pnlListarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnListarAlumnoMouseExited

    private void btnEliminarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoMouseExited
        pnlEliminarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnEliminarAlumnoMouseExited

    private void btnBuscarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseClicked
        FormBuscarAlumno buscar = new FormBuscarAlumno();
        buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBuscarAlumnoMouseClicked

    private void btnActualizarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseClicked
        FormActualizarAlumno actua = new FormActualizarAlumno();
        actua.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnActualizarAlumnoMouseClicked

    private void btnListarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarAlumnoMouseClicked
        FormListarAlumno list = new FormListarAlumno();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarAlumnoMouseClicked

    private void btnEliminarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoMouseClicked
        FormEliminarAlumno elim = new FormEliminarAlumno();
        elim.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarAlumnoMouseClicked

    private void btnAgregarProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProfesorMouseEntered
        pnlAgregarProfesor.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnAgregarProfesorMouseEntered

    private void btnAgregarProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProfesorMouseExited
        pnlAgregarProfesor.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnAgregarProfesorMouseExited

    private void btnBuscarProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProfesorMouseEntered
        pnlBuscarProfesor.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarProfesorMouseEntered

    private void btnBuscarProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProfesorMouseExited
        pnlBuscarProfesor.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarProfesorMouseExited

    private void btnActualizarProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarProfesorMouseEntered
        pnlActualizarProfesor.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarProfesorMouseEntered

    private void btnActualizarProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarProfesorMouseExited
        pnlActualizarProfesor.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarProfesorMouseExited

    private void btnListarProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarProfesorMouseEntered
        pnlListarProfesor.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnListarProfesorMouseEntered

    private void btnListarProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarProfesorMouseExited
        pnlListarProfesor.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnListarProfesorMouseExited

    private void btnEliminarProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProfesorMouseEntered
        pnlEliminarProfesor.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnEliminarProfesorMouseEntered

    private void btnEliminarProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProfesorMouseExited
        pnlEliminarProfesor.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnEliminarProfesorMouseExited

    private void btnAgregarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProfesorMouseClicked
        FormAgregarProfesor agregar = new FormAgregarProfesor();
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarProfesorMouseClicked

    private void btnBuscarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProfesorMouseClicked
        FormBuscarProfesor buscar = new FormBuscarProfesor();
        buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBuscarProfesorMouseClicked

    private void btnActualizarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarProfesorMouseClicked
        FormActualizarProfesor actu = new FormActualizarProfesor();
        actu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnActualizarProfesorMouseClicked

    private void btnListarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarProfesorMouseClicked
        FormListarProfesor list = new FormListarProfesor();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarProfesorMouseClicked

    private void btnEliminarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProfesorMouseClicked
        FormEliminarProfesor elim = new FormEliminarProfesor();
        elim.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarProfesorMouseClicked

    private void btnEliminarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMatriculaMouseClicked
        FormEliminarMatricula elim = new FormEliminarMatricula();
        elim.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarMatriculaMouseClicked

    private void btnEliminarMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMatriculaMouseEntered
        pnlEliminarMatricula.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnEliminarMatriculaMouseEntered

    private void btnEliminarMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMatriculaMouseExited
        pnlEliminarMatricula.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnEliminarMatriculaMouseExited

    private void btnAgregarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMatriculaMouseClicked
        FormAgregarMatricula agregar = new FormAgregarMatricula();
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarMatriculaMouseClicked

    private void btnAgregarMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMatriculaMouseEntered
        pnlAgregarMatricula.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnAgregarMatriculaMouseEntered

    private void btnAgregarMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMatriculaMouseExited
        pnlAgregarMatricula.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnAgregarMatriculaMouseExited

    private void btnBuscarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaMouseClicked
        FormBuscarMatricula buscar = new FormBuscarMatricula();
        buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBuscarMatriculaMouseClicked

    private void btnBuscarMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaMouseEntered
        pnlBuscarMatricula.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarMatriculaMouseEntered

    private void btnBuscarMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMatriculaMouseExited
        pnlBuscarMatricula.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarMatriculaMouseExited

    private void btnActualizarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMatriculaMouseClicked
        FormActualizarMatricula actu = new FormActualizarMatricula();
        actu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnActualizarMatriculaMouseClicked

    private void btnActualizarMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMatriculaMouseEntered
        pnlActualizarMatricula.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarMatriculaMouseEntered

    private void btnActualizarMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMatriculaMouseExited
        pnlActualizarMatricula.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarMatriculaMouseExited

    private void btnListarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMatriculaMouseClicked
        FormListarMatricula list = new FormListarMatricula();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarMatriculaMouseClicked

    private void btnListarMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMatriculaMouseEntered
        pnlListarMatricula.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnListarMatriculaMouseEntered

    private void btnListarMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMatriculaMouseExited
        pnlListarMatricula.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnListarMatriculaMouseExited

    private void txtRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegresarMouseClicked
        FormLogueo list = new FormLogueo();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtRegresarMouseClicked

    private void txtRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegresarMouseEntered
        pnlRegresar.setBackground(new Color(254,199,7));
        txtRegresar.setForeground(Color.white);
    }//GEN-LAST:event_txtRegresarMouseEntered

    private void txtRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegresarMouseExited
        pnlRegresar.setBackground(Color.white);
        txtRegresar.setForeground(Color.black);
    }//GEN-LAST:event_txtRegresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicioAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualizarAlumno;
    private javax.swing.JLabel btnActualizarMatricula;
    private javax.swing.JLabel btnActualizarProfesor;
    private javax.swing.JLabel btnAgregarAlumno;
    private javax.swing.JLabel btnAgregarMatricula;
    private javax.swing.JLabel btnAgregarProfesor;
    private javax.swing.JLabel btnBuscarAlumno;
    private javax.swing.JLabel btnBuscarMatricula;
    private javax.swing.JLabel btnBuscarProfesor;
    private javax.swing.JLabel btnEliminarAlumno;
    private javax.swing.JLabel btnEliminarMatricula;
    private javax.swing.JLabel btnEliminarProfesor;
    private javax.swing.JLabel btnListarAlumno;
    private javax.swing.JLabel btnListarMatricula;
    private javax.swing.JLabel btnListarProfesor;
    private javax.swing.JLabel imagenAlumno;
    private javax.swing.JLabel imagenProfesor;
    private javax.swing.JLabel imagenProfesor1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel pnlActualizarAlumno;
    private javax.swing.JPanel pnlActualizarMatricula;
    private javax.swing.JPanel pnlActualizarProfesor;
    private javax.swing.JPanel pnlAgregarAlumno;
    private javax.swing.JPanel pnlAgregarMatricula;
    private javax.swing.JPanel pnlAgregarProfesor;
    private javax.swing.JPanel pnlBuscarAlumno;
    private javax.swing.JPanel pnlBuscarMatricula;
    private javax.swing.JPanel pnlBuscarProfesor;
    private javax.swing.JPanel pnlEliminarAlumno;
    private javax.swing.JPanel pnlEliminarMatricula;
    private javax.swing.JPanel pnlEliminarProfesor;
    private javax.swing.JPanel pnlListarAlumno;
    private javax.swing.JPanel pnlListarMatricula;
    private javax.swing.JPanel pnlListarProfesor;
    private javax.swing.JPanel pnlRegresar;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel txtActualizarAlumno;
    private javax.swing.JLabel txtActualizarMatricula;
    private javax.swing.JLabel txtActualizarProfesor;
    private javax.swing.JLabel txtAgregarAlumno;
    private javax.swing.JLabel txtAgregarMatricula;
    private javax.swing.JLabel txtAgregarProfesor;
    private javax.swing.JLabel txtBuscarAlumno;
    private javax.swing.JLabel txtBuscarMatricula;
    private javax.swing.JLabel txtBuscarProfesor;
    private javax.swing.JLabel txtEliminarAlumno;
    private javax.swing.JLabel txtEliminarMatricula;
    private javax.swing.JLabel txtEliminarProfesor;
    private javax.swing.JLabel txtListarAlumno;
    private javax.swing.JLabel txtListarMatricula;
    private javax.swing.JLabel txtListarProfesor;
    private javax.swing.JLabel txtRegresar;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
