/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormAgregarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form FormAgregarMatricula
     */
    int xMouse,yMouse;
    Alumno alum;
    Profesor profe;
    RepositorioMySQL repo = new RepositorioMySQL();
    public FormAgregarMatricula() {
        initComponents();
        repo.agregarMatriculaCSV(repo.listarMatricula());
        llenarComboBoxs();
        this.setLocationRelativeTo(null);         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtNombreAlumno = new javax.swing.JTextField();
        nombreAlumno = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cmbNombreAlumno = new javax.swing.JComboBox<>();
        pnlAgregarMatricula = new javax.swing.JPanel();
        btnAgregarMatricula = new javax.swing.JLabel();
        alumnoMatricula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtDniAlumno = new javax.swing.JTextField();
        dniAlumno = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        cmbCursoAlumno = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        txtDniAlumno3 = new javax.swing.JTextField();
        dniAlumno3 = new javax.swing.JLabel();
        cursoAlumno = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        turnoAlumno = new javax.swing.JLabel();
        cmbTurnoAlumno = new javax.swing.JComboBox<>();
        gradoAlumno = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        cmbGradoAlumno = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        txtNombreProfesor = new javax.swing.JTextField();
        nombreProfesor = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        cmbNombreProfesor = new javax.swing.JComboBox<>();
        profesorMatricula = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txtDniProfesor = new javax.swing.JTextField();
        dniProfesor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 370, 10));

        txtNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreAlumno.setToolTipText("");
        txtNombreAlumno.setBorder(null);
        txtNombreAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreAlumnoMousePressed(evt);
            }
        });
        txtNombreAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreAlumnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 370, 30));

        nombreAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreAlumno.setText("Nombre del alumno");
        jPanel1.add(nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 370, 10));

        cmbNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbNombreAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreAlumnoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 370, 30));

        pnlAgregarMatricula.setBackground(new java.awt.Color(254, 199, 7));

        btnAgregarMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnAgregarMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarMatricula.setText("AGREGAR");
        btnAgregarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMatriculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMatriculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMatriculaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarMatriculaLayout = new javax.swing.GroupLayout(pnlAgregarMatricula);
        pnlAgregarMatricula.setLayout(pnlAgregarMatriculaLayout);
        pnlAgregarMatriculaLayout.setHorizontalGroup(
            pnlAgregarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlAgregarMatriculaLayout.setVerticalGroup(
            pnlAgregarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlAgregarMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 130, 40));

        alumnoMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        alumnoMatricula.setText("ALUMNO");
        jPanel1.add(alumnoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel2.setText("AGREGAR MATRICULA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 10));

        txtDniAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDniAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtDniAlumno.setText("Ingerese el dni del alumno...");
        txtDniAlumno.setToolTipText("");
        txtDniAlumno.setBorder(null);
        txtDniAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniAlumnoMousePressed(evt);
            }
        });
        jPanel1.add(txtDniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 370, 30));

        dniAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        dniAlumno.setText("Dni del alumno");
        jPanel1.add(dniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 370, 10));

        cmbCursoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbCursoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbCursoAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCursoAlumnoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCursoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 370, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 10));

        txtDniAlumno3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDniAlumno3.setForeground(new java.awt.Color(102, 102, 102));
        txtDniAlumno3.setText("Ingerese el dni del alumno...");
        txtDniAlumno3.setToolTipText("");
        txtDniAlumno3.setBorder(null);
        txtDniAlumno3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniAlumno3MousePressed(evt);
            }
        });
        jPanel1.add(txtDniAlumno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 370, 30));

        dniAlumno3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        dniAlumno3.setText("Dni del alumno");
        jPanel1.add(dniAlumno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        cursoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        cursoAlumno.setText("Curso del alumno");
        jPanel1.add(cursoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 370, 10));

        turnoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        turnoAlumno.setText("Turno de estudio del alumno");
        jPanel1.add(turnoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        cmbTurnoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbTurnoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion...", "Mañana", "Tarde" }));
        cmbTurnoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(cmbTurnoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 370, 30));

        gradoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        gradoAlumno.setText("Grado escolar del alumno");
        jPanel1.add(gradoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 370, 10));

        cmbGradoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbGradoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion...", "1° grado", "2° grado", "3° grado", "4° grado", "5° grado", "6° grado" }));
        cmbGradoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbGradoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradoAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGradoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 370, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 370, 10));

        txtNombreProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProfesor.setText("Ingerese su nombre completo...");
        txtNombreProfesor.setToolTipText("");
        txtNombreProfesor.setBorder(null);
        txtNombreProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreProfesorMousePressed(evt);
            }
        });
        txtNombreProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProfesorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 370, 30));

        nombreProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor.setText("Nombre del Profesor");
        jPanel1.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 370, 10));

        cmbNombreProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbNombreProfesor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreProfesorItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 370, 30));

        profesorMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        profesorMatricula.setText("PROFESOR");
        jPanel1.add(profesorMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 370, 10));

        txtDniProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDniProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtDniProfesor.setText("Ingerese el dni del profesor...");
        txtDniProfesor.setToolTipText("");
        txtDniProfesor.setBorder(null);
        txtDniProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniProfesorMousePressed(evt);
            }
        });
        txtDniProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniProfesorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDniProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 370, 30));

        dniProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        dniProfesor.setText("Dni del profesor");
        jPanel1.add(dniProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAgregar3.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        FormInicioAdministrador inicio = new FormInicioAdministrador();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtNombreAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreAlumnoMousePressed
        if(txtNombreAlumno.getText().equals("Ingerese su nombre completo...")){
            txtNombreAlumno.setText("");
        }
        txtNombreAlumno.setForeground(Color.black);
        if(txtDniAlumno.getText().equals("")){
            txtDniAlumno.setText("Ingerese el dni del alumno...");
            txtDniAlumno.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreAlumnoMousePressed

    private void btnAgregarMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMatriculaMouseClicked
        Alumno alumno = repo.listarAlumno().stream().filter(p->p.getDniAlumno().equals(txtDniAlumno.getText())).collect(Collectors.toList()).get(0);
        if(repo.buscarPorCodigoMatricula(alumno.getCodAlumno(), cmbCursoAlumno.getSelectedIndex())!=null){
            cmbCursoAlumno.setSelectedIndex(0);
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
            cmbNombreProfesor.setSelectedIndex(0);
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
            JOptionPane.showMessageDialog(this,"El alumno ya ha sido matriculado en el curso escogido");
            txtNombreAlumno.setFocusable(true);
        }else if(txtNombreAlumno.getText().equals("Ingerese su nombre completo...")||txtDniAlumno.getText().equals("Ingerese el dni del alumno...")
            ||cmbCursoAlumno.getSelectedIndex()==0||cmbTurnoAlumno.getSelectedIndex()==0||cmbGradoAlumno.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(this,"Hay un dato o varios en blanco\nPor favor completelos");
        txtNombreAlumno.setFocusable(true);
        }else if(txtDniAlumno.getText().length()!=8){
        JOptionPane.showMessageDialog(this,"El recuadro del dato DniAlumno exceden o no supera\nla cantidad que se necesita");
        txtNombreAlumno.setFocusable(true);
        }else if(txtDniProfesor.getText().length()!=8){
        JOptionPane.showMessageDialog(this,"El recuadro del dato DniProfesor exceden o no supera\nla cantidad que se necesita");
        txtNombreAlumno.setFocusable(true);
        }else{
        int codAlumno = alum.getCodAlumno();
        int codProfe = profe.getCodProfesor();   
        String curso = (String)cmbCursoAlumno.getSelectedItem();
        String turno = cmbTurnoAlumno.getSelectedItem().toString();
        String grado = cmbGradoAlumno.getSelectedItem().toString();
        Curso cr = repo.buscarPorNombreCurso(curso);

        Matricula matri = new Matricula(codAlumno,codProfe,cr.getCodCurso(),turno,grado,"");
        repo.agregarMatricula(matri);
        repo.agregarMatriculaCSV(repo.listarMatricula());

        txtNombreAlumno.setText("Ingerese su nombre completo...");
        cmbNombreAlumno.setSelectedIndex(0);
        txtDniAlumno.setText("Ingerese el dni del alumno...");
        cmbCursoAlumno.setSelectedIndex(0);
        cmbTurnoAlumno.setSelectedIndex(0);
        cmbGradoAlumno.setSelectedIndex(0);
        txtNombreProfesor.setText("Ingerese su nombre completo...");
        cmbNombreProfesor.setSelectedIndex(0);
        txtDniProfesor.setText("Ingerese el dni del profesor...");

        JOptionPane.showMessageDialog(this,"Matricula registrado correctamente :D");
        txtNombreAlumno.setFocusable(true);
        }
        /*Alumno alumno = repo.listarAlumno().stream().filter(p->p.getDniAlumno().equals(txtDniAlumno.getText())).collect(Collectors.toList()).get(0);
        List<Matricula> matricu = repo.listarMatricula().stream().filter(p->p.getCodAlumno()==alumno.getCodAlumno()&&p.getCodCurso()==cmbCursoAlumno.getSelectedIndex()).collect(Collectors.toList());
        if(matricu.isEmpty()){
            if(txtNombreAlumno.getText().equals("Ingerese su nombre completo...")||txtDniAlumno.getText().equals("Ingerese el dni del alumno...")
            ||cmbCursoAlumno.getSelectedIndex()==0||cmbTurnoAlumno.getSelectedIndex()==0||cmbGradoAlumno.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Hay un dato o varios en blanco\nPor favor completelos");
            txtNombreAlumno.setFocusable(true);
            }else if(txtDniAlumno.getText().length()!=8){
            JOptionPane.showMessageDialog(this,"El recuadro del dato DniAlumno exceden o no supera\nla cantidad que se necesita");
            txtNombreAlumno.setFocusable(true);
            }else if(txtDniProfesor.getText().length()!=8){
            JOptionPane.showMessageDialog(this,"El recuadro del dato DniProfesor exceden o no supera\nla cantidad que se necesita");
            txtNombreAlumno.setFocusable(true);
            }else{
            int codAlumno = alum.getCodAlumno();
            int codProfe = profe.getCodProfesor();   
            int curso = cmbCursoAlumno.getSelectedIndex();
            String turno = cmbTurnoAlumno.getSelectedItem().toString();
            String grado = cmbGradoAlumno.getSelectedItem().toString();              

            Matricula matri = new Matricula(codAlumno,codProfe,curso,turno,"",grado);
            repo.agregarMatricula(matri);
            repo.agregarMatriculaCSV(repo.listarMatricula());

            txtNombreAlumno.setText("Ingerese su nombre completo...");
            cmbNombreAlumno.setSelectedIndex(0);
            txtDniAlumno.setText("Ingerese el dni del alumno...");
            cmbCursoAlumno.setSelectedIndex(0);
            cmbTurnoAlumno.setSelectedIndex(0);
            cmbGradoAlumno.setSelectedIndex(0);
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            cmbNombreProfesor.setSelectedIndex(0);
            txtDniProfesor.setText("Ingerese el dni del profesor...");

            JOptionPane.showMessageDialog(this,"Matricula registrado correctamente :D");
            txtNombreAlumno.setFocusable(true);
            }
        }else{
            cmbCursoAlumno.setSelectedIndex(0);
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
            cmbNombreProfesor.setSelectedIndex(0);
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
            JOptionPane.showMessageDialog(this,"El alumno ya ha sido matriculado en el curso escogido");
            txtNombreAlumno.setFocusable(true);        
        }  */  
    }//GEN-LAST:event_btnAgregarMatriculaMouseClicked

    private void btnAgregarMatriculaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMatriculaMouseEntered
        pnlAgregarMatricula.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnAgregarMatriculaMouseEntered

    private void btnAgregarMatriculaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMatriculaMouseExited
        pnlAgregarMatricula.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnAgregarMatriculaMouseExited

    private void txtDniAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniAlumnoMousePressed
        if(txtDniAlumno.getText().equals("Ingerese el dni del alumno...")){
            txtDniAlumno.setText("");
        }
        txtDniAlumno.setForeground(Color.black);
        if(txtNombreAlumno.getText().equals("")){
            txtNombreAlumno.setText("Ingerese su nombre completo...");
            txtNombreAlumno.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDniAlumnoMousePressed

    private void txtDniAlumno3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniAlumno3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniAlumno3MousePressed

    private void txtNombreProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProfesorMousePressed
        if(txtNombreProfesor.getText().equals("Ingerese su nombre completo...")){
            txtNombreProfesor.setText("");
        }
        txtNombreProfesor.setForeground(Color.black);
        if(txtDniProfesor.getText().equals("")){
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreProfesorMousePressed

    private void txtDniProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniProfesorMousePressed
        if(txtDniProfesor.getText().equals("Ingerese el dni del profesor...")){
            txtDniProfesor.setText("");
        }
        txtDniProfesor.setForeground(Color.black);
        if(txtNombreProfesor.getText().equals("")){
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDniProfesorMousePressed

    private void txtNombreProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfesorActionPerformed

    private void txtDniProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniProfesorActionPerformed

    private void txtNombreAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAlumnoKeyReleased
        busarYPonerComboNombreAlumno();
    }//GEN-LAST:event_txtNombreAlumnoKeyReleased

    private void cmbNombreAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNombreAlumnoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if(cmbNombreAlumno.getSelectedIndex()!=0){
                txtNombreAlumno.setText((String)cmbNombreAlumno.getSelectedItem());
                txtNombreAlumno.setForeground(Color.black);
                alum = repo.listarAlumno().stream().filter(p->p.getNameAlumno().equals((String)cmbNombreAlumno.getSelectedItem())).collect(Collectors.toList()).get(0);
                //alum = repo.buscarPorNombreAlumno(txtNombreAlumno.getText());
                txtDniAlumno.setText((String)alum.getDniAlumno());
                txtDniAlumno.setForeground(Color.black);
            }
        }
    }//GEN-LAST:event_cmbNombreAlumnoItemStateChanged

    private void cmbCursoAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCursoAlumnoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if(cmbCursoAlumno.getSelectedIndex()!=0){
                String curso = (String)cmbCursoAlumno.getSelectedItem();
                Curso cr = repo.buscarPorNombreCurso(curso);
                cmbNombreProfesor.removeAllItems();
                cmbNombreProfesor.addItem("Elija un nombre...");
                for(Profesor x:repo.listarProfesor()){
                    
                    if(x.getCodCurso()==cr.getCodCurso()){
                        cmbNombreProfesor.addItem(x.getNameProfesor());
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbCursoAlumnoItemStateChanged

    private void cmbNombreProfesorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNombreProfesorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if(cmbNombreProfesor.getSelectedIndex()!=0){
            txtNombreProfesor.setText((String)cmbNombreProfesor.getSelectedItem());
            txtNombreProfesor.setForeground(Color.black);
            profe = repo.listarProfesor().stream().filter(p->p.getNameProfesor().equals((String)cmbNombreProfesor.getSelectedItem())).collect(Collectors.toList()).get(0);
            txtDniProfesor.setText((String)profe.getDniProfesor());
            txtDniProfesor.setForeground(Color.black);                        
            }
        }
    }//GEN-LAST:event_cmbNombreProfesorItemStateChanged

    private void cmbGradoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGradoAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgregarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgregarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoMatricula;
    private javax.swing.JLabel btnAgregarMatricula;
    private javax.swing.JComboBox<String> cmbCursoAlumno;
    private javax.swing.JComboBox<String> cmbGradoAlumno;
    private javax.swing.JComboBox<String> cmbNombreAlumno;
    private javax.swing.JComboBox<String> cmbNombreProfesor;
    private javax.swing.JComboBox<String> cmbTurnoAlumno;
    private javax.swing.JLabel cursoAlumno;
    private javax.swing.JLabel dniAlumno;
    private javax.swing.JLabel dniAlumno3;
    private javax.swing.JLabel dniProfesor;
    private javax.swing.JLabel gradoAlumno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JPanel pnlAgregarMatricula;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel profesorMatricula;
    private javax.swing.JLabel turnoAlumno;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtDniAlumno3;
    private javax.swing.JTextField txtDniProfesor;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
    
    void llenarComboBoxs(){
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getEstadoAlumno()==1){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }            
        }       
        cmbNombreProfesor.addItem("Elija un nombre...");
        cmbCursoAlumno.addItem("Elija un curso...");
        for(Curso x:repo.listarCurso()){
            if(x.getCodCurso()!=1){
            cmbCursoAlumno.addItem(x.getNameCurso());                
            }
        }         
    }
    
    void busarYPonerComboNombreAlumno(){
        cmbNombreAlumno.removeAllItems();
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getNameAlumno().toLowerCase().contains(txtNombreAlumno.getText().toLowerCase())){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }
        }
    }
       
}
