/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class FormActualizarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form FormActualizarMatricula
     */
    int xMouse,yMouse; // Creamos variables int que referenciaran al mouse
    RepositorioMySQL repo = new RepositorioMySQL(); // Instanciamos a la clase RepositorioSQL para todos los metodos 
    public FormActualizarMatricula() {
        initComponents();
        // Con esto ponemos el diseño predeterminado que tendra nuestro programa y con la otra funcion llenamos los comboBoxs
        repo.agregarMatriculaCSV(repo.listarMatricula());
        llenarComboBoxs();
        txtDiseno();     
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreAlumno = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cursoAlumno = new javax.swing.JLabel();
        txtCursoAlumno = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        turnoAlumno = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        gradoAlumno = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        profesorMatricula = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        txtGradoAlumno = new javax.swing.JTextField();
        txtTurnoAlumno = new javax.swing.JTextField();
        codigoMatricula = new javax.swing.JLabel();
        txtCodigoMatricula = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtNombreABuscarAlumno = new javax.swing.JTextField();
        nombreABuscar = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        cmbNombreAlumno = new javax.swing.JComboBox<>();
        nombreABuscarCurso = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        cmbNombreCurso = new javax.swing.JComboBox<>();
        pnlBuscarAlumno = new javax.swing.JPanel();
        btnBuscarAlumno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        alumnoMatricula = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        cmbCursoNuevoAlumno = new javax.swing.JComboBox<>();
        cursoNuevoAlumno = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        turnoAlumno1 = new javax.swing.JLabel();
        cmbTurnoNuevoAlumno = new javax.swing.JComboBox<>();
        gradoAlumno1 = new javax.swing.JLabel();
        cmbGradoNuevoAlumno = new javax.swing.JComboBox<>();
        nombreProfesor1 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        cmbNombreNuevoProfesor = new javax.swing.JComboBox<>();
        jSeparator17 = new javax.swing.JSeparator();
        pnlActualizarAlumno = new javax.swing.JPanel();
        btnActualizarAlumno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel2.setText("DATOS NUEVOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        nombreAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreAlumno.setText("Nombre del alumno");
        jPanel1.add(nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreAlumno.setText("Se mostrara el nombre aqui...");
        txtNombreAlumno.setToolTipText("");
        txtNombreAlumno.setBorder(null);
        txtNombreAlumno.setEnabled(false);
        jPanel1.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 370, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 370, 10));

        cursoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        cursoAlumno.setText("Curso del alumno");
        jPanel1.add(cursoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txtCursoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCursoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtCursoAlumno.setText("Se mostrara el curso aqui...");
        txtCursoAlumno.setToolTipText("");
        txtCursoAlumno.setBorder(null);
        txtCursoAlumno.setEnabled(false);
        jPanel1.add(txtCursoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 370, 10));

        turnoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        turnoAlumno.setText("Turno de estudio del alumno");
        jPanel1.add(turnoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 370, 10));

        gradoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        gradoAlumno.setText("Grado escolar del alumno");
        jPanel1.add(gradoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 370, 10));

        profesorMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        profesorMatricula.setText("PROFESOR");
        jPanel1.add(profesorMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        nombreProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor.setText("Nombre del Profesor");
        jPanel1.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        txtNombreProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProfesor.setText("Se mostrara el nombre aqui...");
        txtNombreProfesor.setToolTipText("");
        txtNombreProfesor.setBorder(null);
        txtNombreProfesor.setEnabled(false);
        jPanel1.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 370, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 370, 10));

        txtGradoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtGradoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtGradoAlumno.setText("Se mostrara el grado escolar aqui...");
        txtGradoAlumno.setToolTipText("");
        txtGradoAlumno.setBorder(null);
        txtGradoAlumno.setEnabled(false);
        jPanel1.add(txtGradoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 370, 30));

        txtTurnoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtTurnoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtTurnoAlumno.setText("Se mostrara el turno de estudio aqui...");
        txtTurnoAlumno.setToolTipText("");
        txtTurnoAlumno.setBorder(null);
        txtTurnoAlumno.setEnabled(false);
        jPanel1.add(txtTurnoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 370, 30));

        codigoMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        codigoMatricula.setText("Codigo de la matricula");
        jPanel1.add(codigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtCodigoMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCodigoMatricula.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoMatricula.setText("Se mostrara el codigo aqui...");
        txtCodigoMatricula.setToolTipText("");
        txtCodigoMatricula.setBorder(null);
        txtCodigoMatricula.setEnabled(false);
        jPanel1.add(txtCodigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 370, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 370, 10));

        txtNombreABuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreABuscarAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreABuscarAlumno.setToolTipText("");
        txtNombreABuscarAlumno.setBorder(null);
        txtNombreABuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreABuscarAlumnoMousePressed(evt);
            }
        });
        txtNombreABuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreABuscarAlumnoActionPerformed(evt);
            }
        });
        txtNombreABuscarAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreABuscarAlumnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreABuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 370, 30));

        nombreABuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreABuscar.setText("Nombre del alumno a BUSCAR");
        jPanel1.add(nombreABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 370, 10));

        cmbNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbNombreAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreAlumnoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 370, 30));

        nombreABuscarCurso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreABuscarCurso.setText("Nombre del curso a BUSCAR");
        jPanel1.add(nombreABuscarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 370, 10));

        cmbNombreCurso.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(cmbNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 370, 30));

        pnlBuscarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnBuscarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAlumnoLayout = new javax.swing.GroupLayout(pnlBuscarAlumno);
        pnlBuscarAlumno.setLayout(pnlBuscarAlumnoLayout);
        pnlBuscarAlumnoLayout.setHorizontalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlBuscarAlumnoLayout.setVerticalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel3.setText("ACTUALIZAR MATRICULA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        alumnoMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        alumnoMatricula.setText("ALUMNO");
        jPanel1.add(alumnoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 370, 10));

        cmbCursoNuevoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbCursoNuevoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbCursoNuevoAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCursoNuevoAlumnoItemStateChanged(evt);
            }
        });
        cmbCursoNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursoNuevoAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCursoNuevoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 370, 30));

        cursoNuevoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        cursoNuevoAlumno.setText("Curso NUEVO del alumno");
        jPanel1.add(cursoNuevoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 370, 10));

        turnoAlumno1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        turnoAlumno1.setText("Turno de estudio NUEVO del alumno");
        jPanel1.add(turnoAlumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        cmbTurnoNuevoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbTurnoNuevoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion...", "Mañana", "Tarde" }));
        cmbTurnoNuevoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(cmbTurnoNuevoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 370, 30));

        gradoAlumno1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        gradoAlumno1.setText("Grado escolar NUEVO del alumno");
        jPanel1.add(gradoAlumno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        cmbGradoNuevoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbGradoNuevoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opcion...", "1° grado", "2° grado", "3° grado", "4° grado", "5° grado", "6° grado" }));
        cmbGradoNuevoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbGradoNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradoNuevoAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGradoNuevoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 370, 30));

        nombreProfesor1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor1.setText("Asignacion NUEVO Profesor");
        jPanel1.add(nombreProfesor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, -1));

        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 370, 10));

        cmbNombreNuevoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreNuevoProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(cmbNombreNuevoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 370, 30));

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 370, 10));

        pnlActualizarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnActualizarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnActualizarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarAlumno.setText("ACTUALIZAR");
        btnActualizarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarAlumnoLayout = new javax.swing.GroupLayout(pnlActualizarAlumno);
        pnlActualizarAlumno.setLayout(pnlActualizarAlumnoLayout);
        pnlActualizarAlumnoLayout.setHorizontalGroup(
            pnlActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlActualizarAlumnoLayout.setVerticalGroup(
            pnlActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPredeAlumno.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        // Volvemos al formularioInicioAdministrador
        FormInicioAdministrador inicio = new FormInicioAdministrador();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        // Creamos un evento cuando el mouse entra para que cambie de color y del texto
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        // Creamos un evento cuando el mouse sale para que se restaure el color y del texto
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // Creamos un evento en el cual se ejecuta cuando arrastramos el programa
        // Se obtienen las coordenadas actuales del ratón en la pantalla del programa
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // Se mueve el componente JPanel arrastrándolo según las diferencias de coordenadas
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // Se capturan las coordenadas del ratón cuando se presiona
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtNombreABuscarAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreABuscarAlumnoMousePressed
        // Creamos un metodo en el cual se ejecuta cuando presionamos en el cuadro de texto
        // Evaluamos el txt selecionado y ponemos el texto predeterminado si el usuario no pone nada
        if(txtNombreABuscarAlumno.getText().equals("Ingerese su nombre completo...")){
            txtNombreABuscarAlumno.setText("");
        }
        txtNombreABuscarAlumno.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreABuscarAlumnoMousePressed

    private void txtNombreABuscarAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreABuscarAlumnoKeyReleased
        // Creamos un evento en el cual se ejecuta cada ves que escribimos en el txtNombreABuscarAlumno y llamamos a la funcion 
        busarYPonerComboNombreAlumno();
    }//GEN-LAST:event_txtNombreABuscarAlumnoKeyReleased

    private void cmbNombreAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNombreAlumnoItemStateChanged
        // Creamos un evento en el cual se ejecuta cuando seleccionamos un item del comboBox
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Ponemos esta condicional para que no evalue el indice 0
            if(cmbNombreAlumno.getSelectedIndex()!=0){
                // El item selecionado del comboBox se excribe en el txt
                txtNombreABuscarAlumno.setText((String)cmbNombreAlumno.getSelectedItem());
                txtNombreABuscarAlumno.setForeground(Color.black);
                // Removemos los items y buscamos al alumno seleccionado, luego hacemos un for que recorra la listaMatricula el cual 
                // nos retornara en los cursos que ha sido matriculado el alumno
                cmbNombreCurso.removeAllItems();
                cmbNombreCurso.addItem("Elija un curso...");
                Alumno alum = repo.buscarPorNombreAlumno(txtNombreABuscarAlumno.getText());
                for(Matricula x:repo.listarMatricula()){
                    if(x.getCodAlumno()==alum.getCodAlumno()){
                        Curso curso = repo.buscarPorCodigoCurso(x.getCodCurso());
                        cmbNombreCurso.addItem(curso.getNameCurso());
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbNombreAlumnoItemStateChanged

    private void btnBuscarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseClicked
        // Creamos un evento en el cual se ejecuta cuando hacemos click en el boton
        // Ponemos una condicional para evaluar si hay texto en el txtNombreABuscarAlumno
        if(txtNombreABuscarAlumno.getText().equals("")||cmbNombreCurso.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"No ha digitado ni un nombre para hacer la busqueda");
            txtNombreABuscarAlumno.setFocusable(true);
            txtCodigoMatricula.setText("Se mostrara el codigo aqui...");
            txtNombreAlumno.setText("Se mostrara el nombre aqui...");
            txtCursoAlumno.setText("Se mostrara el curso aqui...");
            txtTurnoAlumno.setText("Se mostrara el turno de estudio aqui...");
            txtGradoAlumno.setText("Se mostrara el grado escolar aqui...");
            txtNombreProfesor.setText("Se mostrara el nombre aqui...");
        }else{
            // Despues de pasar el filtro buscamos el objeto
            // Utilizamos el nombre del alumno para poder buscar con el metodo buscarPorNombreAlumno
            // Utilizamos el nombre del curso para poder buscar con el metodo buscarPorNombreCurso
            Alumno alum = repo.buscarPorNombreAlumno(txtNombreABuscarAlumno.getText());
            Curso cursos = repo.buscarPorNombreCurso((String)cmbNombreCurso.getSelectedItem());
            Matricula matriculaBuscado = repo.buscarPorCodigoMatricula(alum.getCodAlumno(),cursos.getCodCurso());
            Profesor profe = repo.buscarPorCodigoProfesor(matriculaBuscado.getCodProfesor());
            
            // Despues de obtener el objeto buscado lo asignamos a variables
            int codigo = matriculaBuscado.getCodMatricula();
            String nombre = alum.getNameAlumno();
            String curso = cursos.getNameCurso();
            String turno = matriculaBuscado.getTurnoEstudio();
            String grado = matriculaBuscado.getGradoEscolar();
            String nombrePro = profe.getNameProfesor();

            //Aqui le damos el color negro y colocamos las varibles string en los txts
            txtCodigoMatricula.setDisabledTextColor(Color.BLACK);
            txtNombreAlumno.setDisabledTextColor(Color.BLACK);
            txtCursoAlumno.setDisabledTextColor(Color.BLACK);
            txtTurnoAlumno.setDisabledTextColor(Color.BLACK);
            txtGradoAlumno.setDisabledTextColor(Color.BLACK);
            txtNombreProfesor.setDisabledTextColor(Color.BLACK);

            txtCodigoMatricula.setText(Integer.toString(codigo));
            txtNombreAlumno.setText(nombre);
            txtCursoAlumno.setText(curso);
            txtTurnoAlumno.setText(turno);
            txtGradoAlumno.setText(grado);
            txtNombreProfesor.setText(nombrePro);
        }
    }//GEN-LAST:event_btnBuscarAlumnoMouseClicked

    private void btnBuscarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseEntered
        // Creamos un evento cuando el mouse entra para que cambie el color del panel
        pnlBuscarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarAlumnoMouseEntered

    private void btnBuscarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseExited
        // Creamos un evento cuando el mouse sale para que se restaure el color del panel
        pnlBuscarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarAlumnoMouseExited

    private void cmbCursoNuevoAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCursoNuevoAlumnoItemStateChanged
        // Creamos un evento en el cual se ejecuta cuando seleccionamos un item del comboBox
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Ponemos esta condicional para que no evalue el indice 0
            if(cmbCursoNuevoAlumno.getSelectedIndex()!=0){
                String curso = (String)cmbCursoNuevoAlumno.getSelectedItem();
                Curso cr = repo.buscarPorNombreCurso(curso);
                // Removemos los items y buscamos al alumno seleccionado, luego hacemos un for que recorra la listarProfesor el cual 
                // nos retornara en los profesores que enseñan ese curso
                cmbNombreNuevoProfesor.removeAllItems();
                cmbNombreNuevoProfesor.addItem("Elija un nombre...");
                for(Profesor x:repo.listarProfesor()){
                    if(x.getCodCurso()==cr.getCodCurso()){
                        cmbNombreNuevoProfesor.addItem(x.getNameProfesor());
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbCursoNuevoAlumnoItemStateChanged

    private void cmbGradoNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradoNuevoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGradoNuevoAlumnoActionPerformed

    private void btnActualizarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseClicked
        // Creamos un evento en el cual se ejecuta cuando hacemos click en el boton
        // Ponemos una condicional para evaluar si hay texto en el txtNombreABuscar
        if(cmbTurnoNuevoAlumno.getSelectedIndex()==0||cmbGradoNuevoAlumno.getSelectedIndex()==0||cmbNombreNuevoProfesor.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Hay un dato o varios en blanco\nPor favor completelos");
            txtNombreAlumno.setFocusable(true);
        }else{
            // Despues de pasar los filtros se actualizaran los datos de la matricula
            // Utilizamos el nombre para poder buscar con el metodo buscarPorNombreAlumno
            Alumno alum = repo.buscarPorNombreAlumno(txtNombreABuscarAlumno.getText());
            int codAlumno = alum.getCodAlumno();
            Profesor profe = repo.buscarPorNombreProfesor((String)cmbNombreNuevoProfesor.getSelectedItem());
            int codProfe = profe.getCodProfesor();   
            // Se crean las variables que extraeran de los txts que tienen los datos nuevos
            String curso = (String)cmbCursoNuevoAlumno.getSelectedItem();
            String turno = cmbTurnoNuevoAlumno.getSelectedItem().toString();
            String grado = cmbGradoNuevoAlumno.getSelectedItem().toString();
            Curso cr = repo.buscarPorNombreCurso(curso);
            
            // Creamos un objeto con los datos nuevo y lo mandamos al metodo actualizarAlumno que tiene como parametro
            // el objeto con los nuevos datos y el codigo del alumno para hacer el cambio respectivo
            Matricula matri = new Matricula(codAlumno,codProfe,cr.getCodCurso(),turno,"",grado);
            repo.actualizarMatricula(matri,Integer.parseInt(txtCodigoMatricula.getText()));
            repo.agregarMatriculaCSV(repo.listarMatricula());
            // Vaciamos los cuadros de texto y ponemos el diseño predeterminado que escogimos y al final enviamos un mensaje
            vaciarTxt();
            txtDiseno();
            JOptionPane.showMessageDialog(this,"Matricula actualizada correctamente :D");
            txtNombreAlumno.setFocusable(true);
        }        
    }//GEN-LAST:event_btnActualizarAlumnoMouseClicked

    private void btnActualizarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseEntered
        // Creamos un evento cuando el mouse entra para que cambie el color del panel
        pnlActualizarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarAlumnoMouseEntered

    private void btnActualizarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseExited
        // Creamos un evento cuando el mouse sale para que se restaure el color del panel
        pnlActualizarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarAlumnoMouseExited

    private void cmbCursoNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursoNuevoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursoNuevoAlumnoActionPerformed

    private void txtNombreABuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreABuscarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreABuscarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormActualizarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormActualizarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormActualizarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormActualizarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormActualizarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoMatricula;
    private javax.swing.JLabel btnActualizarAlumno;
    private javax.swing.JLabel btnBuscarAlumno;
    private javax.swing.JComboBox<String> cmbCursoNuevoAlumno;
    private javax.swing.JComboBox<String> cmbGradoNuevoAlumno;
    private javax.swing.JComboBox<String> cmbNombreAlumno;
    private javax.swing.JComboBox<String> cmbNombreCurso;
    private javax.swing.JComboBox<String> cmbNombreNuevoProfesor;
    private javax.swing.JComboBox<String> cmbTurnoNuevoAlumno;
    private javax.swing.JLabel codigoMatricula;
    private javax.swing.JLabel cursoAlumno;
    private javax.swing.JLabel cursoNuevoAlumno;
    private javax.swing.JLabel gradoAlumno;
    private javax.swing.JLabel gradoAlumno1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel nombreABuscar;
    private javax.swing.JLabel nombreABuscarCurso;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JLabel nombreProfesor1;
    private javax.swing.JPanel pnlActualizarAlumno;
    private javax.swing.JPanel pnlBuscarAlumno;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel profesorMatricula;
    private javax.swing.JLabel turnoAlumno;
    private javax.swing.JLabel turnoAlumno1;
    private javax.swing.JTextField txtCodigoMatricula;
    private javax.swing.JTextField txtCursoAlumno;
    private javax.swing.JTextField txtGradoAlumno;
    private javax.swing.JTextField txtNombreABuscarAlumno;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JTextField txtTurnoAlumno;
    // End of variables declaration//GEN-END:variables
    
    // Creamos un funcion en el cual tendra el diseño predeterminado que tendra los txt enabled
    private void txtDiseno(){
        Border disabledBorder = BorderFactory.createLineBorder(Color.white);      
        txtCodigoMatricula.setBorder(disabledBorder);
        txtCodigoMatricula.setDisabledTextColor(Color.GRAY);        
        txtNombreAlumno.setBorder(disabledBorder);
        txtNombreAlumno.setDisabledTextColor(Color.GRAY);
        txtCursoAlumno.setBorder(disabledBorder);
        txtCursoAlumno.setDisabledTextColor(Color.GRAY);
        txtTurnoAlumno.setBorder(disabledBorder);
        txtTurnoAlumno.setDisabledTextColor(Color.GRAY);
        txtGradoAlumno.setBorder(disabledBorder);
        txtGradoAlumno.setDisabledTextColor(Color.GRAY);
        txtNombreProfesor.setBorder(disabledBorder);
        txtNombreProfesor.setDisabledTextColor(Color.GRAY);       
    }
    
    // En esta funcion se utilizara para llenar el comboBox con el nombre o las coincidencias que encuentra con todos los nombres de cada objeto Alumno
    void busarYPonerComboNombreAlumno(){
        cmbNombreAlumno.removeAllItems();
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getNameAlumno().toLowerCase().contains(txtNombreABuscarAlumno.getText().toLowerCase())){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }
        }
    }
    
    //Llenamos el comboBox del Curso, Alumno y CursoProfesor
    private void llenarComboBoxs(){
        cmbCursoNuevoAlumno.addItem("Elija un curso...");
        for(Curso x:repo.listarCurso()){
            if(x.getCodCurso()!=1){
            cmbCursoNuevoAlumno.addItem(x.getNameCurso());                
            }
        }    
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            cmbNombreAlumno.addItem(x.getNameAlumno());
        }
        cmbNombreCurso.addItem("Elija un curso...");
        cmbNombreNuevoProfesor.addItem("Elija un nombre...");
    } 
    
    // Vaciamos todos los txts con los mensajes predeterminados
    void vaciarTxt(){
            txtCodigoMatricula.setText("Se mostrara el codigo aqui...");
            txtNombreAlumno.setText("Se mostrara el nombre aqui...");
            txtCursoAlumno.setText("Se mostrara el curso aqui...");
            txtTurnoAlumno.setText("Se mostrara el turno de estudio aqui...");
            txtGradoAlumno.setText("Se mostrara el grado escolar aqui...");
            txtNombreProfesor.setText("Se mostrara el nombre aqui...");          
            txtNombreABuscarAlumno.setText("Ingerese su nombre completo...");
            txtNombreABuscarAlumno.setForeground(Color.gray);
            cmbNombreAlumno.setSelectedIndex(0);
            cmbNombreCurso.setSelectedIndex(0);
            cmbCursoNuevoAlumno.setSelectedIndex(0);
            cmbTurnoNuevoAlumno.setSelectedIndex(0);
            cmbGradoNuevoAlumno.setSelectedIndex(0);
            cmbNombreNuevoProfesor.setSelectedIndex(0);               
    }
}
