/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class FormEliminarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form FormEliminarMatricula
     */
    int xMouse,yMouse;
    RepositorioMySQL repo = new RepositorioMySQL();      
    public FormEliminarMatricula() {
        initComponents();
        llenarComboBoxs();
        txtDiseno();
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alumnoMatricula = new javax.swing.JLabel();
        nombreAlumno = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cursoAlumno = new javax.swing.JLabel();
        txtCursoAlumno = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        turnoAlumno = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        gradoAlumno = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        profesorMatricula = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        txtGradoAlumno = new javax.swing.JTextField();
        txtTurnoAlumno = new javax.swing.JTextField();
        codigoMatricula = new javax.swing.JLabel();
        txtCodigoMatricula = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtNombreABuscarAlumno = new javax.swing.JTextField();
        nombreABuscar = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        cmbNombreAlumno = new javax.swing.JComboBox<>();
        nombreABuscarCurso = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        cmbNombreCurso = new javax.swing.JComboBox<>();
        pnlBuscarAlumno = new javax.swing.JPanel();
        btnBuscarAlumno = new javax.swing.JLabel();
        pnlEliminarAlumno = new javax.swing.JPanel();
        btnEliminarAlumno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel2.setText("ELIMINAR DATOS DE LA MATRICULA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        alumnoMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        alumnoMatricula.setText("ALUMNO");
        jPanel1.add(alumnoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        nombreAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreAlumno.setText("Nombre del alumno");
        jPanel1.add(nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreAlumno.setText("Se mostrara el nombre aqui...");
        txtNombreAlumno.setToolTipText("");
        txtNombreAlumno.setBorder(null);
        txtNombreAlumno.setEnabled(false);
        jPanel1.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 370, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 370, 10));

        cursoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        cursoAlumno.setText("Curso del alumno");
        jPanel1.add(cursoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txtCursoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCursoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtCursoAlumno.setText("Se mostrara el curso aqui...");
        txtCursoAlumno.setToolTipText("");
        txtCursoAlumno.setBorder(null);
        txtCursoAlumno.setEnabled(false);
        jPanel1.add(txtCursoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 370, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 370, 10));

        turnoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        turnoAlumno.setText("Turno de estudio del alumno");
        jPanel1.add(turnoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 370, 10));

        gradoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        gradoAlumno.setText("Grado escolar del alumno");
        jPanel1.add(gradoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 370, 10));

        profesorMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        profesorMatricula.setText("PROFESOR");
        jPanel1.add(profesorMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        nombreProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor.setText("Nombre del Profesor");
        jPanel1.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        txtNombreProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProfesor.setText("Se mostrara el nombre aqui...");
        txtNombreProfesor.setToolTipText("");
        txtNombreProfesor.setBorder(null);
        txtNombreProfesor.setEnabled(false);
        jPanel1.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 370, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 370, 10));

        txtGradoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtGradoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtGradoAlumno.setText("Se mostrara el grado escolar aqui...");
        txtGradoAlumno.setToolTipText("");
        txtGradoAlumno.setBorder(null);
        txtGradoAlumno.setEnabled(false);
        jPanel1.add(txtGradoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 370, 30));

        txtTurnoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtTurnoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtTurnoAlumno.setText("Se mostrara el turno de estudio aqui...");
        txtTurnoAlumno.setToolTipText("");
        txtTurnoAlumno.setBorder(null);
        txtTurnoAlumno.setEnabled(false);
        jPanel1.add(txtTurnoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 370, 30));

        codigoMatricula.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        codigoMatricula.setText("Codigo de la matricula");
        jPanel1.add(codigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtCodigoMatricula.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCodigoMatricula.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoMatricula.setText("Se mostrara el codigo aqui...");
        txtCodigoMatricula.setToolTipText("");
        txtCodigoMatricula.setBorder(null);
        txtCodigoMatricula.setEnabled(false);
        txtCodigoMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoMatriculaMousePressed(evt);
            }
        });
        jPanel1.add(txtCodigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 370, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 370, 10));

        txtNombreABuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreABuscarAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreABuscarAlumno.setToolTipText("");
        txtNombreABuscarAlumno.setBorder(null);
        txtNombreABuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreABuscarAlumnoMousePressed(evt);
            }
        });
        txtNombreABuscarAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreABuscarAlumnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreABuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 370, 30));

        nombreABuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreABuscar.setText("Nombre del alumno a BUSCAR");
        jPanel1.add(nombreABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 370, 10));

        cmbNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbNombreAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreAlumnoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 370, 30));

        nombreABuscarCurso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreABuscarCurso.setText("Nombre del curso a BUSCAR");
        jPanel1.add(nombreABuscarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 370, 10));

        cmbNombreCurso.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(cmbNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 370, 30));

        pnlBuscarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnBuscarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAlumnoLayout = new javax.swing.GroupLayout(pnlBuscarAlumno);
        pnlBuscarAlumno.setLayout(pnlBuscarAlumnoLayout);
        pnlBuscarAlumnoLayout.setHorizontalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlBuscarAlumnoLayout.setVerticalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, -1, -1));

        pnlEliminarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnEliminarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnEliminarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarAlumno.setText("ELIMINAR");
        btnEliminarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlEliminarAlumnoLayout = new javax.swing.GroupLayout(pnlEliminarAlumno);
        pnlEliminarAlumno.setLayout(pnlEliminarAlumnoLayout);
        pnlEliminarAlumnoLayout.setHorizontalGroup(
            pnlEliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlEliminarAlumnoLayout.setVerticalGroup(
            pnlEliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoEliminar3.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        FormInicioAdministrador inicio = new FormInicioAdministrador();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtCodigoMatriculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMatriculaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMatriculaMousePressed

    private void txtNombreABuscarAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreABuscarAlumnoMousePressed
        if(txtNombreABuscarAlumno.getText().equals("Ingerese su nombre completo...")){
            txtNombreABuscarAlumno.setText("");
        }
        txtNombreABuscarAlumno.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreABuscarAlumnoMousePressed

    private void txtNombreABuscarAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreABuscarAlumnoKeyReleased
        busarYPonerComboNombreAlumno();
    }//GEN-LAST:event_txtNombreABuscarAlumnoKeyReleased

    private void cmbNombreAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNombreAlumnoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if(cmbNombreAlumno.getSelectedIndex()!=0){
                txtNombreABuscarAlumno.setText((String)cmbNombreAlumno.getSelectedItem());
                txtNombreABuscarAlumno.setForeground(Color.black);
                cmbNombreCurso.removeAllItems();
                cmbNombreCurso.addItem("Elija un curso...");
                Alumno alum = repo.buscarPorNombreAlumno(txtNombreABuscarAlumno.getText());
                for(Matricula x:repo.listarMatricula()){
                    if(x.getCodAlumno()==alum.getCodAlumno()){
                        Curso curso = repo.buscarPorCodigoCurso(x.getCodCurso());
                        cmbNombreCurso.addItem(curso.getNameCurso());
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbNombreAlumnoItemStateChanged

    private void btnBuscarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseClicked
        if(txtNombreABuscarAlumno.getText().equals("")||cmbNombreCurso.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"No ha digitado ni un nombre para hacer la busqueda");
            txtNombreABuscarAlumno.setFocusable(true);
            txtCodigoMatricula.setText("Se mostrara el codigo aqui...");
            txtNombreAlumno.setText("Se mostrara el nombre aqui...");
            txtCursoAlumno.setText("Se mostrara el curso aqui...");
            txtTurnoAlumno.setText("Se mostrara el turno de estudio aqui...");
            txtGradoAlumno.setText("Se mostrara el grado escolar aqui...");
            txtNombreProfesor.setText("Se mostrara el nombre aqui...");
        }else{
            Alumno alum = repo.buscarPorNombreAlumno(txtNombreABuscarAlumno.getText());
            Curso cursos = repo.buscarPorNombreCurso((String)cmbNombreCurso.getSelectedItem());
            Matricula matriculaBuscado = repo.buscarPorCodigoMatricula(alum.getCodAlumno(),cursos.getCodCurso());
            Profesor profe = repo.buscarPorCodigoProfesor(matriculaBuscado.getCodProfesor());

            int codigo = matriculaBuscado.getCodMatricula();
            String nombre = alum.getNameAlumno();
            String curso = cursos.getNameCurso();
            String turno = matriculaBuscado.getTurnoEstudio();
            String grado = matriculaBuscado.getGradoEscolar();
            String nombrePro = profe.getNameProfesor();

            txtCodigoMatricula.setDisabledTextColor(Color.BLACK);
            txtNombreAlumno.setDisabledTextColor(Color.BLACK);
            txtCursoAlumno.setDisabledTextColor(Color.BLACK);
            txtTurnoAlumno.setDisabledTextColor(Color.BLACK);
            txtGradoAlumno.setDisabledTextColor(Color.BLACK);
            txtNombreProfesor.setDisabledTextColor(Color.BLACK);

            txtCodigoMatricula.setText(Integer.toString(codigo));
            txtNombreAlumno.setText(nombre);
            txtCursoAlumno.setText(curso);
            txtTurnoAlumno.setText(turno);
            txtGradoAlumno.setText(grado);
            txtNombreProfesor.setText(nombrePro);
        }
    }//GEN-LAST:event_btnBuscarAlumnoMouseClicked

    private void btnBuscarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseEntered
        pnlBuscarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarAlumnoMouseEntered

    private void btnBuscarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseExited
        pnlBuscarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarAlumnoMouseExited

    private void btnEliminarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoMouseClicked
        repo.eliminarMatricula(Integer.parseInt(txtCodigoMatricula.getText()));
        vaciarTxt();
        txtDiseno();
        JOptionPane.showMessageDialog(this,"Datos del matricula eliminado correctamente :D");
        txtNombreABuscarAlumno.setFocusable(true);
    }//GEN-LAST:event_btnEliminarAlumnoMouseClicked

    private void btnEliminarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoMouseEntered
        pnlEliminarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnEliminarAlumnoMouseEntered

    private void btnEliminarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoMouseExited
        pnlEliminarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnEliminarAlumnoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEliminarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEliminarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEliminarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEliminarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEliminarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumnoMatricula;
    private javax.swing.JLabel btnBuscarAlumno;
    private javax.swing.JLabel btnEliminarAlumno;
    private javax.swing.JComboBox<String> cmbNombreAlumno;
    private javax.swing.JComboBox<String> cmbNombreCurso;
    private javax.swing.JLabel codigoMatricula;
    private javax.swing.JLabel cursoAlumno;
    private javax.swing.JLabel gradoAlumno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel nombreABuscar;
    private javax.swing.JLabel nombreABuscarCurso;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JPanel pnlBuscarAlumno;
    private javax.swing.JPanel pnlEliminarAlumno;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel profesorMatricula;
    private javax.swing.JLabel turnoAlumno;
    private javax.swing.JTextField txtCodigoMatricula;
    private javax.swing.JTextField txtCursoAlumno;
    private javax.swing.JTextField txtGradoAlumno;
    private javax.swing.JTextField txtNombreABuscarAlumno;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JTextField txtTurnoAlumno;
    // End of variables declaration//GEN-END:variables
    void txtDiseno(){
        Border disabledBorder = BorderFactory.createLineBorder(Color.white);      
        txtCodigoMatricula.setBorder(disabledBorder);
        txtCodigoMatricula.setDisabledTextColor(Color.GRAY);        
        txtNombreAlumno.setBorder(disabledBorder);
        txtNombreAlumno.setDisabledTextColor(Color.GRAY);
        txtCursoAlumno.setBorder(disabledBorder);
        txtCursoAlumno.setDisabledTextColor(Color.GRAY);
        txtTurnoAlumno.setBorder(disabledBorder);
        txtTurnoAlumno.setDisabledTextColor(Color.GRAY);
        txtGradoAlumno.setBorder(disabledBorder);
        txtGradoAlumno.setDisabledTextColor(Color.GRAY);
        txtNombreProfesor.setBorder(disabledBorder);
        txtNombreProfesor.setDisabledTextColor(Color.GRAY);       
    }
    
    void busarYPonerComboNombreAlumno(){
        cmbNombreAlumno.removeAllItems();
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getNameAlumno().toLowerCase().contains(txtNombreABuscarAlumno.getText().toLowerCase())){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }
        }
    } 
    
    void llenarComboBoxs(){
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getEstadoAlumno()==1){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }            
        }       
        cmbNombreCurso.addItem("Elija un curso...");        
    }
    
    void vaciarTxt(){
            txtCodigoMatricula.setText("Se mostrara el codigo aqui...");
            txtNombreAlumno.setText("Se mostrara el nombre aqui...");
            txtCursoAlumno.setText("Se mostrara el curso aqui...");
            txtTurnoAlumno.setText("Se mostrara el turno de estudio aqui...");
            txtGradoAlumno.setText("Se mostrara el grado escolar aqui...");
            txtNombreProfesor.setText("Se mostrara el nombre aqui...");          
            txtNombreABuscarAlumno.setText("Ingerese su nombre completo...");
            txtNombreABuscarAlumno.setForeground(Color.gray);
            cmbNombreAlumno.setSelectedIndex(0);
            cmbNombreCurso.setSelectedIndex(0);              
    }    
}
