/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormAgregarProfesor extends javax.swing.JFrame {

    /**
     * Creates new form FormAgregarAlumno
     */
    int xMouse,yMouse;
    RepositorioMySQL repo = new RepositorioMySQL();    
    public FormAgregarProfesor() {
        initComponents();
        repo.agregarProfesorCSV(repo.listarProfesor());
        repo.agregarUsuarioCSV(repo.listarUsuario());
        llenarCombo();
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        agregarProfesor = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JLabel();
        txtApellidoProfesor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        apellidoProfesor = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombreProfesor = new javax.swing.JTextField();
        correoProfesor = new javax.swing.JLabel();
        txtCorreoProfesor = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtDniProfesor = new javax.swing.JTextField();
        dniProfesor = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        generoAlumno = new javax.swing.JLabel();
        cmbCursoProfesor = new javax.swing.JComboBox<>();
        pnlAgregarAlumno = new javax.swing.JPanel();
        btnAgregarAlumno = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtTelefonoProfesor = new javax.swing.JTextField();
        telefonoProfesor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        agregarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        agregarProfesor.setText("AGREGAR PROFESOR");
        jPanel1.add(agregarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        nombreProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor.setText("Nombre completo");
        jPanel1.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtApellidoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtApellidoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoProfesor.setText("Ingerese su apellido completo...");
        txtApellidoProfesor.setToolTipText("");
        txtApellidoProfesor.setBorder(null);
        txtApellidoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoProfesorMousePressed(evt);
            }
        });
        txtApellidoProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoProfesorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoProfesorKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 440, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 440, 10));

        apellidoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoProfesor.setText("Apellido completo");
        jPanel1.add(apellidoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 440, 10));

        txtNombreProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProfesor.setToolTipText("");
        txtNombreProfesor.setBorder(null);
        txtNombreProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreProfesorMousePressed(evt);
            }
        });
        txtNombreProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProfesorKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 440, 30));

        correoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        correoProfesor.setText("Correo personal");
        jPanel1.add(correoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txtCorreoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCorreoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreoProfesor.setText("Ingerese su correo personal...");
        txtCorreoProfesor.setToolTipText("");
        txtCorreoProfesor.setBorder(null);
        txtCorreoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtCorreoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 440, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 440, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 440, 10));

        txtDniProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDniProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtDniProfesor.setText("Ingerese el dni del profesor...");
        txtDniProfesor.setToolTipText("");
        txtDniProfesor.setBorder(null);
        txtDniProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniProfesorMousePressed(evt);
            }
        });
        txtDniProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniProfesorKeyTyped(evt);
            }
        });
        jPanel1.add(txtDniProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 440, 30));

        dniProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        dniProfesor.setText("Dni del profesor");
        jPanel1.add(dniProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 440, 10));

        generoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        generoAlumno.setText("Especialidad del profesor");
        jPanel1.add(generoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        cmbCursoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbCursoProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(cmbCursoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 440, 30));

        pnlAgregarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnAgregarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnAgregarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarAlumno.setText("AGREGAR");
        btnAgregarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarAlumnoLayout = new javax.swing.GroupLayout(pnlAgregarAlumno);
        pnlAgregarAlumno.setLayout(pnlAgregarAlumnoLayout);
        pnlAgregarAlumnoLayout.setHorizontalGroup(
            pnlAgregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlAgregarAlumnoLayout.setVerticalGroup(
            pnlAgregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 130, 40));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 440, 10));

        txtTelefonoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtTelefonoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefonoProfesor.setText("Ingerese el telefono del profesor...");
        txtTelefonoProfesor.setToolTipText("");
        txtTelefonoProfesor.setBorder(null);
        txtTelefonoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoProfesorMousePressed(evt);
            }
        });
        txtTelefonoProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoProfesorKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefonoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 440, 30));

        telefonoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        telefonoProfesor.setText("Telefono del profesor");
        jPanel1.add(telefonoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAgregar2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
       FormInicioAdministrador inicio = new FormInicioAdministrador();
       inicio.setVisible(true);
       dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtApellidoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoProfesorMousePressed
        if(txtApellidoProfesor.getText().equals("Ingerese su apellido completo...")){
            txtApellidoProfesor.setText("");
        }
        txtApellidoProfesor.setForeground(Color.black);
        if(txtNombreProfesor.getText().equals("")){
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
        }
        if(txtCorreoProfesor.getText().equals("")){
            txtCorreoProfesor.setText("Ingerese su correo personal...");
            txtCorreoProfesor.setForeground(Color.gray);
        }
        if(txtDniProfesor.getText().equals("")){
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
        }
        if(txtTelefonoProfesor.getText().equals("")){
            txtTelefonoProfesor.setText("Ingerese el telefono del profesor...");
            txtTelefonoProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtApellidoProfesorMousePressed

    private void txtNombreProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProfesorMousePressed
        if(txtNombreProfesor.getText().equals("Ingerese su nombre completo...")){
            txtNombreProfesor.setText("");
        }       
        txtNombreProfesor.setForeground(Color.black);        
        if(txtApellidoProfesor.getText().equals("")){
            txtApellidoProfesor.setText("Ingerese su apellido completo...");
            txtApellidoProfesor.setForeground(Color.gray);
        }
        if(txtCorreoProfesor.getText().equals("")){
            txtCorreoProfesor.setText("Ingerese su correo personal...");
            txtCorreoProfesor.setForeground(Color.gray);
        }
        if(txtDniProfesor.getText().equals("")){
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
        }
        if(txtTelefonoProfesor.getText().equals("")){
            txtTelefonoProfesor.setText("Ingerese el telefono del profesor...");
            txtTelefonoProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreProfesorMousePressed

    private void txtCorreoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoProfesorMousePressed
        if(txtCorreoProfesor.getText().equals("Ingerese su correo personal...")){
            txtCorreoProfesor.setText("");
        }   
        txtCorreoProfesor.setForeground(Color.black);
        if(txtApellidoProfesor.getText().equals("")){
            txtApellidoProfesor.setText("Ingerese su apellido completo...");
            txtApellidoProfesor.setForeground(Color.gray);
        }
        if(txtNombreProfesor.getText().equals("")){
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
        }
        if(txtDniProfesor.getText().equals("")){
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
        }
        if(txtTelefonoProfesor.getText().equals("")){
            txtTelefonoProfesor.setText("Ingerese el telefono del profesor...");
            txtTelefonoProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoProfesorMousePressed

    private void txtDniProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniProfesorMousePressed
        if(txtDniProfesor.getText().equals("Ingerese el dni del profesor...")){
            txtDniProfesor.setText("");
        }   
        txtDniProfesor.setForeground(Color.black);
        if(txtApellidoProfesor.getText().equals("")){
            txtApellidoProfesor.setText("Ingerese su apellido completo...");
            txtApellidoProfesor.setForeground(Color.gray);
        }
        if(txtNombreProfesor.getText().equals("")){
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
        }
        if(txtCorreoProfesor.getText().equals("")){
            txtCorreoProfesor.setText("Ingerese su correo personal...");
            txtCorreoProfesor.setForeground(Color.gray);
        }
        if(txtTelefonoProfesor.getText().equals("")){
            txtTelefonoProfesor.setText("Ingerese el telefono del profesor...");
            txtTelefonoProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDniProfesorMousePressed

    private void btnAgregarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoMouseClicked
        // Obtenemos todos los datos primero
        String nombre = txtNombreProfesor.getText();
        String apellido = txtApellidoProfesor.getText();
        String telefono = txtTelefonoProfesor.getText();
        String correo = txtCorreoProfesor.getText();
        String dni = txtDniProfesor.getText();

        // 1. (Tu código) Verifica DNI duplicado
        if (repo.mismoProfesor(dni)) {
            JOptionPane.showMessageDialog(this, "Este profesor ya ha sido registrado en la base de datos (Dni)");
            txtNombreProfesor.setFocusable(true);
        
        // 2. (Tu código) Verifica campos obligatorios vacíos (CON TYPOS CORREGIDOS)
        } else if (nombre.equals("Ingerese su nombre completo...") || nombre.isEmpty() ||
                   apellido.equals("Ingerese su apellido completo...") || apellido.isEmpty() ||
                   telefono.equals("Ingerese el telefono del profesor...") || telefono.isEmpty() || // <-- CORREGIDO
                   correo.equals("Ingerese su correo personal...") || correo.isEmpty() ||
                   dni.equals("Ingerese el dni del profesor...") || dni.isEmpty() || // <-- CORREGIDO
                   cmbCursoProfesor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Hay un dato o varios en blanco\nPor favor completelos");
            txtNombreProfesor.setFocusable(true);
        
        // 3. INICIO DE VALIDACIONES DE FORMATO (reemplaza tu 'else if(comprobarDni())')
        } else {
            // Definir Expresiones Regulares (Regex)
            String dniRegex = "^\\d{8}$"; // Exactamente 8 dígitos
            String telRegex = "^\\d{9}$"; // Exactamente 9 dígitos
            String textoRegex = "^[a-zA-Z\\s]+$"; // Solo letras y espacios
            
            // --- Cadena de validación ---
            if (!dni.matches(dniRegex)) {
                JOptionPane.showMessageDialog(this, "El 'Dni del profesor' debe contener exactamente 8 dígitos numéricos.");
                txtDniProfesor.setFocusable(true);
            } else if (!telefono.matches(telRegex)) {
                JOptionPane.showMessageDialog(this, "El 'Telefono del profesor' debe contener exactamente 9 dígitos numéricos.");
                txtTelefonoProfesor.setFocusable(true);
            } else if (!nombre.matches(textoRegex)) {
                JOptionPane.showMessageDialog(this, "El 'Nombre completo' solo debe contener letras y espacios.");
                txtNombreProfesor.setFocusable(true);
            } else if (nombre.length() > 50) {
                JOptionPane.showMessageDialog(this, "El 'Nombre completo' no debe exceder los 50 caracteres.");
                txtNombreProfesor.setFocusable(true);
            } else if (!apellido.matches(textoRegex)) {
                JOptionPane.showMessageDialog(this, "El 'Apellido completo' solo debe contener letras y espacios.");
                txtApellidoProfesor.setFocusable(true);
            } else if (apellido.length() > 50) {
                JOptionPane.showMessageDialog(this, "El 'Apellido completo' no debe exceder los 50 caracteres.");
                txtApellidoProfesor.setFocusable(true);
            
            // 4. ¡TODAS LAS VALIDACIONES PASARON!
            } else {
                // (Tu código para agregar a la BD)
                String curso = (String) cmbCursoProfesor.getSelectedItem();
                Curso cr = repo.buscarPorNombreCurso(curso);
                Profesor profe = new Profesor(nombre, apellido, telefono, correo, dni, cr.getCodCurso());
                repo.agregarProfesor(profe);
                repo.agregarProfesorCSV(repo.listarProfesor());

                // (Tu código para limpiar campos)
                txtNombreProfesor.setText("Ingerese su nombre completo...");
                txtNombreProfesor.setForeground(Color.gray);
                txtApellidoProfesor.setText("Ingerese su apellido completo...");
                txtApellidoProfesor.setForeground(Color.gray);
                txtTelefonoProfesor.setText("Ingerese el telefono del profesor...");
                txtTelefonoProfesor.setForeground(Color.gray);
                txtCorreoProfesor.setText("Ingerese su correo personal...");
                txtCorreoProfesor.setForeground(Color.gray);
                txtDniProfesor.setText("Ingerese el dni del profesor...");
                txtDniProfesor.setForeground(Color.gray);
                cmbCursoProfesor.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Profesor registrado correctamente :D");
                txtNombreProfesor.setFocusable(true);
            }
        }
    }//GEN-LAST:event_btnAgregarAlumnoMouseClicked

    private void btnAgregarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoMouseEntered
        pnlAgregarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnAgregarAlumnoMouseEntered

    private void btnAgregarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarAlumnoMouseExited
        pnlAgregarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnAgregarAlumnoMouseExited

    private void txtApellidoProfesorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoProfesorKeyReleased
        String name = repo.extraerNombre(txtNombreProfesor.getText()).toLowerCase();
        String ape = repo.extraerNombre(txtApellidoProfesor.getText()).toLowerCase();
        
        String nombres = name+"."+ape+"@usil.pe";
        txtCorreoProfesor.setText(nombres);
        txtCorreoProfesor.setForeground(Color.black);
    }//GEN-LAST:event_txtApellidoProfesorKeyReleased

    private void txtTelefonoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoProfesorMousePressed
        if(txtTelefonoProfesor.getText().equals("Ingerese el telefono del profesor...")){
            txtTelefonoProfesor.setText("");
        }   
        txtTelefonoProfesor.setForeground(Color.black);
        if(txtApellidoProfesor.getText().equals("")){
            txtApellidoProfesor.setText("Ingerese su apellido completo...");
            txtApellidoProfesor.setForeground(Color.gray);
        }
        if(txtNombreProfesor.getText().equals("")){
            txtNombreProfesor.setText("Ingerese su nombre completo...");
            txtNombreProfesor.setForeground(Color.gray);
        }
        if(txtCorreoProfesor.getText().equals("")){
            txtCorreoProfesor.setText("Ingerese su correo personal...");
            txtCorreoProfesor.setForeground(Color.gray);
        }
        if(txtDniProfesor.getText().equals("")){
            txtDniProfesor.setText("Ingerese el dni del profesor...");
            txtDniProfesor.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtTelefonoProfesorMousePressed

    private void txtNombreProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProfesorKeyTyped
        char c = evt.getKeyChar();
            if (!Character.isLetter(c) && (c != ' ') && (c != java.awt.event.KeyEvent.VK_BACK_SPACE)) {
                evt.consume(); 
            }
            if (txtNombreProfesor.getText().length() >= 50 && txtNombreProfesor.getSelectedText() == null) {
                evt.consume();
            }
    }//GEN-LAST:event_txtNombreProfesorKeyTyped

    private void txtApellidoProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoProfesorKeyTyped
        char c = evt.getKeyChar();
            if (!Character.isLetter(c) && (c != ' ') && (c != java.awt.event.KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
            }
            if (txtApellidoProfesor.getText().length() >= 50 && txtApellidoProfesor.getSelectedText() == null) {
                evt.consume();
            }
    }//GEN-LAST:event_txtApellidoProfesorKeyTyped

    private void txtTelefonoProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoProfesorKeyTyped
char c = evt.getKeyChar();
    if (!Character.isDigit(c) && (c != java.awt.event.KeyEvent.VK_BACK_SPACE)) {
        evt.consume();
    }
    if (txtTelefonoProfesor.getText().length() >= 9 && txtTelefonoProfesor.getSelectedText() == null) {
        evt.consume();
    }
    }//GEN-LAST:event_txtTelefonoProfesorKeyTyped

    private void txtDniProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniProfesorKeyTyped
    char c = evt.getKeyChar();
        if (!Character.isDigit(c) && (c != java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (txtDniProfesor.getText().length() >= 8 && txtDniProfesor.getSelectedText() == null) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDniProfesorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgregarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgregarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarProfesor;
    private javax.swing.JLabel apellidoProfesor;
    private javax.swing.JLabel btnAgregarAlumno;
    private javax.swing.JComboBox<String> cmbCursoProfesor;
    private javax.swing.JLabel correoProfesor;
    private javax.swing.JLabel dniProfesor;
    private javax.swing.JLabel generoAlumno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JPanel pnlAgregarAlumno;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel telefonoProfesor;
    private javax.swing.JTextField txtApellidoProfesor;
    private javax.swing.JTextField txtCorreoProfesor;
    private javax.swing.JTextField txtDniProfesor;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JTextField txtTelefonoProfesor;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo() {
        cmbCursoProfesor.addItem("Elija una opcion...");
        for(int i=0;i<repo.listarCurso().size();i++){
            if(repo.listarCurso().get(i).getCodCurso()!=1){
            cmbCursoProfesor.addItem(repo.listarCurso().get(i).getNameCurso());                
            }
        }
    }
    
    private boolean comprobarDni(){
        String dni = txtDniProfesor.getText();

        // Verificar que tenga exactamente 8 dígitos
        if(dni.length() != 8){
            JOptionPane.showMessageDialog(this, 
                "El DNI debe tener exactamente 8 dígitos.\n" +
                "Actualmente tiene: " + dni.length() + " caracteres",
                "DNI inválido",
                JOptionPane.WARNING_MESSAGE);
            txtDniProfesor.requestFocus();
            return false;
        }

        // Verificar que todos sean números
        for(char c : dni.toCharArray()){
            if(!Character.isDigit(c)){
                JOptionPane.showMessageDialog(this, 
                    "El DNI solo debe contener números.\n" +
                    "Se encontró un carácter inválido: '" + c + "'",
                    "DNI inválido",
                    JOptionPane.WARNING_MESSAGE);
                txtDniProfesor.requestFocus();
                return false;
            }
        }

        return true;
    }
}
