/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class FormBuscarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form FormBuscarAlumno
     */
    int xMouse,yMouse;
    RepositorioMySQL repo = new RepositorioMySQL();  
    FormLogueo logueo = new FormLogueo();
    public FormBuscarAlumno() {
        repo.agregarAlumnoCSV(repo.listarAlumno());
        initComponents();
        llenarComboBoxs();
        txtDiseno();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtGeneroAlumno = new javax.swing.JTextField();
        dniAlumno = new javax.swing.JLabel();
        actualizarAlumno = new javax.swing.JLabel();
        generoAlumno = new javax.swing.JLabel();
        correoAlumno = new javax.swing.JLabel();
        txtApellidoAlumno = new javax.swing.JTextField();
        txtNombreABuscar = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        nombreAlumno = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        apellidoAlumno = new javax.swing.JLabel();
        txtCorreoAlumno = new javax.swing.JTextField();
        nombreABuscar = new javax.swing.JLabel();
        txtDniAlumno = new javax.swing.JTextField();
        pnlBuscarAlumno = new javax.swing.JPanel();
        btnBuscarAlumno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        txtCodigoAlumno = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        codigoAlumno = new javax.swing.JLabel();
        cmbNombreAlumno = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 300, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 300, 10));

        txtGeneroAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtGeneroAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtGeneroAlumno.setText("Se mostrara el genero aqui...");
        txtGeneroAlumno.setToolTipText("");
        txtGeneroAlumno.setBorder(null);
        txtGeneroAlumno.setEnabled(false);
        txtGeneroAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtGeneroAlumnoMousePressed(evt);
            }
        });
        jPanel1.add(txtGeneroAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 300, 30));

        dniAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        dniAlumno.setText("Dni del alumno");
        jPanel1.add(dniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        actualizarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        actualizarAlumno.setText("BUSCAR DATOS DEL ALUMNO");
        jPanel1.add(actualizarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        generoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        generoAlumno.setText("Genero del alumno");
        jPanel1.add(generoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        correoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        correoAlumno.setText("Correo personal");
        jPanel1.add(correoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        txtApellidoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtApellidoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoAlumno.setText("Se mostrara el apellido aqui...");
        txtApellidoAlumno.setToolTipText("");
        txtApellidoAlumno.setBorder(null);
        txtApellidoAlumno.setEnabled(false);
        txtApellidoAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoAlumnoMousePressed(evt);
            }
        });
        jPanel1.add(txtApellidoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 300, 30));

        txtNombreABuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreABuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreABuscar.setToolTipText("");
        txtNombreABuscar.setBorder(null);
        txtNombreABuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreABuscarMousePressed(evt);
            }
        });
        txtNombreABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreABuscarActionPerformed(evt);
            }
        });
        txtNombreABuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreABuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 300, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 300, 10));

        nombreAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreAlumno.setText("Nombre completo");
        jPanel1.add(nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        txtNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreAlumno.setText("Se mostrara el nombre aqui...");
        txtNombreAlumno.setToolTipText("");
        txtNombreAlumno.setBorder(null);
        txtNombreAlumno.setEnabled(false);
        txtNombreAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreAlumnoMousePressed(evt);
            }
        });
        txtNombreAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreAlumnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 300, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 300, 10));

        apellidoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoAlumno.setText("Apellido completo");
        jPanel1.add(apellidoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtCorreoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCorreoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreoAlumno.setText("Se mostrara el correo aqui...");
        txtCorreoAlumno.setToolTipText("");
        txtCorreoAlumno.setBorder(null);
        txtCorreoAlumno.setEnabled(false);
        txtCorreoAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoAlumnoMousePressed(evt);
            }
        });
        jPanel1.add(txtCorreoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 300, 30));

        nombreABuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreABuscar.setText("Nombre del alumno a BUSCAR");
        jPanel1.add(nombreABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        txtDniAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDniAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtDniAlumno.setText("Se mostrara el dni aqui...");
        txtDniAlumno.setToolTipText("");
        txtDniAlumno.setBorder(null);
        txtDniAlumno.setEnabled(false);
        txtDniAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniAlumnoMousePressed(evt);
            }
        });
        jPanel1.add(txtDniAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 300, 30));

        pnlBuscarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnBuscarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAlumnoLayout = new javax.swing.GroupLayout(pnlBuscarAlumno);
        pnlBuscarAlumno.setLayout(pnlBuscarAlumnoLayout);
        pnlBuscarAlumnoLayout.setHorizontalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlBuscarAlumnoLayout.setVerticalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtCodigoAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCodigoAlumno.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoAlumno.setText("Se mostrara el codigo aqui...");
        txtCodigoAlumno.setToolTipText("");
        txtCodigoAlumno.setBorder(null);
        txtCodigoAlumno.setEnabled(false);
        txtCodigoAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoAlumnoMousePressed(evt);
            }
        });
        jPanel1.add(txtCodigoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 300, 30));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 300, 10));

        codigoAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        codigoAlumno.setText("Codigo de Alumno");
        jPanel1.add(codigoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        cmbNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbNombreAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreAlumnoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 300, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 300, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoBuscar.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeneroAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGeneroAlumnoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroAlumnoMousePressed

    private void txtApellidoAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoAlumnoMousePressed
        if(txtNombreABuscar.getText().equals("Ingerese el nombre a buscar...")){
            txtNombreABuscar.setText("");
        }
    }//GEN-LAST:event_txtApellidoAlumnoMousePressed

    private void txtNombreABuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreABuscarMousePressed
        if(txtNombreABuscar.getText().equals("Ingerese el nombre a buscar...")){
            txtNombreABuscar.setText("");
        }
        txtNombreABuscar.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreABuscarMousePressed

    private void txtNombreABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreABuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreABuscarActionPerformed

    private void txtNombreAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreAlumnoMousePressed

    }//GEN-LAST:event_txtNombreAlumnoMousePressed

    private void txtNombreAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAlumnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoKeyReleased

    private void txtCorreoAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoAlumnoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoAlumnoMousePressed

    private void txtDniAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniAlumnoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniAlumnoMousePressed

    private void btnBuscarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseClicked
        if(txtNombreABuscar.getText().equals("")||txtNombreABuscar.getText().equals("Ingerese el nombre a buscar...")){
            JOptionPane.showMessageDialog(this,"No ha digitado ni un nombre para hacer la busqueda");
            txtNombreAlumno.setFocusable(true);
            txtCodigoAlumno.setText("Se mostrara el codigo aqui...");
            txtNombreAlumno.setText("Se mostrara el nombre aqui...");
            txtApellidoAlumno.setText("Se mostrara el apellido aqui...");
            txtCorreoAlumno.setText("Se mostrara el correo aqui...");
            txtDniAlumno.setText("Se mostrara el dni aqui...");
            txtGeneroAlumno.setText("Se mostrara el curso aqui...");
        }else if(repo.buscarPorNombreAlumno(txtNombreABuscar.getText())==null){
            JOptionPane.showMessageDialog(this,"El nombre digitado no existe");
            txtNombreAlumno.setFocusable(true);
            txtCodigoAlumno.setText("Se mostrara el codigo aqui...");
            txtNombreAlumno.setText("Se mostrara el nombre aqui...");
            txtApellidoAlumno.setText("Se mostrara el apellido aqui...");
            txtCorreoAlumno.setText("Se mostrara el correo aqui...");
            txtDniAlumno.setText("Se mostrara el dni aqui...");
            txtGeneroAlumno.setText("Se mostrara el curso aqui...");
        }else{
            String nombres = txtNombreABuscar.getText();
            Alumno alumnoBuscado = repo.buscarPorNombreAlumno(nombres);
            //List<Alumno> alumnoBuscado = text.buscarAlumno(cod);

            int codigo = alumnoBuscado.getCodAlumno();
            String nombre = alumnoBuscado.getNameAlumno();
            String apellido = alumnoBuscado.getApellidoAlumno();
            String correo = alumnoBuscado.getCorreoAlumno();
            String dni = alumnoBuscado.getDniAlumno();
            String genero = repo.obtenerGenero(alumnoBuscado);

            txtCodigoAlumno.setDisabledTextColor(Color.BLACK);       
            txtNombreAlumno.setDisabledTextColor(Color.BLACK);
            txtApellidoAlumno.setDisabledTextColor(Color.BLACK);
            txtCorreoAlumno.setDisabledTextColor(Color.BLACK);
            txtDniAlumno.setDisabledTextColor(Color.BLACK);
            txtGeneroAlumno.setDisabledTextColor(Color.BLACK);            
            txtCodigoAlumno.setText(Integer.toString(codigo));
            txtNombreAlumno.setText(nombre);
            txtApellidoAlumno.setText(apellido);
            txtCorreoAlumno.setText(correo);
            txtDniAlumno.setText(dni);
            txtGeneroAlumno.setText(genero);
        }
    }//GEN-LAST:event_btnBuscarAlumnoMouseClicked

    private void btnBuscarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseEntered
        pnlBuscarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarAlumnoMouseEntered

    private void btnBuscarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseExited
        pnlBuscarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarAlumnoMouseExited

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        if(logueo.vis!=1){
            FormInicioAdministrador inicio = new FormInicioAdministrador();
            inicio.setVisible(true);
            dispose();            
        }else{
            FormInicioProfesor inicio = new FormInicioProfesor();
            inicio.setVisible(true);
            dispose();            
        }
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtCodigoAlumnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoAlumnoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAlumnoMousePressed

    private void cmbNombreAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNombreAlumnoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if(cmbNombreAlumno.getSelectedIndex()!=0){
                txtNombreABuscar.setText((String)cmbNombreAlumno.getSelectedItem());
                txtNombreABuscar.setForeground(Color.black);
                cmbNombreAlumno.removeAllItems();
            }
        }
    }//GEN-LAST:event_cmbNombreAlumnoItemStateChanged

    private void txtNombreABuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreABuscarKeyReleased
        busarYPonerComboNombreAlumno();
    }//GEN-LAST:event_txtNombreABuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuscarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizarAlumno;
    private javax.swing.JLabel apellidoAlumno;
    private javax.swing.JLabel btnBuscarAlumno;
    private javax.swing.JComboBox<String> cmbNombreAlumno;
    private javax.swing.JLabel codigoAlumno;
    private javax.swing.JLabel correoAlumno;
    private javax.swing.JLabel dniAlumno;
    private javax.swing.JLabel generoAlumno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nombreABuscar;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JPanel pnlBuscarAlumno;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextField txtCodigoAlumno;
    private javax.swing.JTextField txtCorreoAlumno;
    private javax.swing.JTextField txtDniAlumno;
    private javax.swing.JTextField txtGeneroAlumno;
    private javax.swing.JTextField txtNombreABuscar;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
    void txtDiseno(){
        Border disabledBorder = BorderFactory.createLineBorder(Color.white);
        txtCodigoAlumno.setBorder(disabledBorder);
        txtCodigoAlumno.setDisabledTextColor(Color.GRAY);       
        txtNombreAlumno.setBorder(disabledBorder);
        txtNombreAlumno.setDisabledTextColor(Color.GRAY);
        txtApellidoAlumno.setBorder(disabledBorder);
        txtApellidoAlumno.setDisabledTextColor(Color.GRAY);
        txtCorreoAlumno.setBorder(disabledBorder);
        txtCorreoAlumno.setDisabledTextColor(Color.GRAY);
        txtDniAlumno.setBorder(disabledBorder);
        txtDniAlumno.setDisabledTextColor(Color.GRAY);
        txtGeneroAlumno.setBorder(disabledBorder);
        txtGeneroAlumno.setDisabledTextColor(Color.GRAY);        
    }
    
    private void busarYPonerComboNombreAlumno(){
        cmbNombreAlumno.removeAllItems();
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getNameAlumno().toLowerCase().contains(txtNombreABuscar.getText().toLowerCase())){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }
        }
    } 
    
    private void llenarComboBoxs(){
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Alumno x:repo.listarAlumno()){
            if(x.getEstadoAlumno()==1){
                cmbNombreAlumno.addItem(x.getNameAlumno());
            }            
        }            
    }    
}
