/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class FormBuscarProfesor extends javax.swing.JFrame {

    /**
     * Creates new form FormBuscarAlumno
     */
    int xMouse,yMouse;
    RepositorioMySQL repo = new RepositorioMySQL();     
    public FormBuscarProfesor() {
        initComponents();
        llenarComboBoxs();
        txtDiseno();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtCursoProfesor = new javax.swing.JTextField();
        dniProfesor = new javax.swing.JLabel();
        actualizarAlumno = new javax.swing.JLabel();
        cursoProfesor = new javax.swing.JLabel();
        correoProfesor = new javax.swing.JLabel();
        txtApellidoProfesor = new javax.swing.JTextField();
        txtNombreABuscar = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        nombreProfesor = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        apellidoProfesor = new javax.swing.JLabel();
        txtCorreoProfesor = new javax.swing.JTextField();
        nombreABuscar = new javax.swing.JLabel();
        txtDniProfesor = new javax.swing.JTextField();
        pnlBuscarAlumno = new javax.swing.JPanel();
        btnBuscarAlumno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        txtCodigoProfesor = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        codigoProfesor = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtTelefonoProfesor = new javax.swing.JTextField();
        telefonoProfesor = new javax.swing.JLabel();
        cmbNombreAlumno = new javax.swing.JComboBox<>();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 300, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 300, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 300, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 300, 10));

        txtCursoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCursoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtCursoProfesor.setText("Se mostrara el curso aqui...");
        txtCursoProfesor.setToolTipText("");
        txtCursoProfesor.setBorder(null);
        txtCursoProfesor.setEnabled(false);
        txtCursoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCursoProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtCursoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 300, 30));

        dniProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        dniProfesor.setText("Dni del Profesor");
        jPanel1.add(dniProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        actualizarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        actualizarAlumno.setText("BUSCAR DATOS DEL PROFESOR");
        jPanel1.add(actualizarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        cursoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        cursoProfesor.setText("Curso del Profesor");
        jPanel1.add(cursoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        correoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        correoProfesor.setText("Correo personal");
        jPanel1.add(correoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        txtApellidoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtApellidoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoProfesor.setText("Se mostrara el apellido aqui...");
        txtApellidoProfesor.setToolTipText("");
        txtApellidoProfesor.setBorder(null);
        txtApellidoProfesor.setEnabled(false);
        txtApellidoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtApellidoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 300, 30));

        txtNombreABuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreABuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreABuscar.setToolTipText("");
        txtNombreABuscar.setBorder(null);
        txtNombreABuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreABuscarMousePressed(evt);
            }
        });
        txtNombreABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreABuscarActionPerformed(evt);
            }
        });
        txtNombreABuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreABuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 300, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 300, 10));

        nombreProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor.setText("Nombre completo");
        jPanel1.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtNombreProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNombreProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProfesor.setText("Se mostrara el nombre aqui...");
        txtNombreProfesor.setToolTipText("");
        txtNombreProfesor.setBorder(null);
        txtNombreProfesor.setEnabled(false);
        txtNombreProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreProfesorMousePressed(evt);
            }
        });
        txtNombreProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProfesorKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 300, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 300, 10));

        apellidoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoProfesor.setText("Apellido completo");
        jPanel1.add(apellidoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        txtCorreoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCorreoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreoProfesor.setText("Se mostrara el correo aqui...");
        txtCorreoProfesor.setToolTipText("");
        txtCorreoProfesor.setBorder(null);
        txtCorreoProfesor.setEnabled(false);
        txtCorreoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtCorreoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 300, 30));

        nombreABuscar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreABuscar.setText("Nombre a BUSCAR");
        jPanel1.add(nombreABuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        txtDniProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDniProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtDniProfesor.setText("Se mostrara el dni aqui...");
        txtDniProfesor.setToolTipText("");
        txtDniProfesor.setBorder(null);
        txtDniProfesor.setEnabled(false);
        txtDniProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDniProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtDniProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 300, 30));

        pnlBuscarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnBuscarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAlumnoLayout = new javax.swing.GroupLayout(pnlBuscarAlumno);
        pnlBuscarAlumno.setLayout(pnlBuscarAlumnoLayout);
        pnlBuscarAlumnoLayout.setHorizontalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlBuscarAlumnoLayout.setVerticalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtCodigoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCodigoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoProfesor.setText("Se mostrara el codigo aqui...");
        txtCodigoProfesor.setToolTipText("");
        txtCodigoProfesor.setBorder(null);
        txtCodigoProfesor.setEnabled(false);
        txtCodigoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtCodigoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 300, 30));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 300, 10));

        codigoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        codigoProfesor.setText("Codigo de Profesor");
        jPanel1.add(codigoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 300, 10));

        txtTelefonoProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtTelefonoProfesor.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefonoProfesor.setText("Se mostrara el telefono aqui...");
        txtTelefonoProfesor.setToolTipText("");
        txtTelefonoProfesor.setBorder(null);
        txtTelefonoProfesor.setEnabled(false);
        txtTelefonoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoProfesorMousePressed(evt);
            }
        });
        jPanel1.add(txtTelefonoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 300, 30));

        telefonoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        telefonoProfesor.setText("Telefono del Profesor");
        jPanel1.add(telefonoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        cmbNombreAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbNombreAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbNombreAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNombreAlumnoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 300, 30));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 300, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoBuscar2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCursoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCursoProfesorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoProfesorMousePressed

    private void txtApellidoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoProfesorMousePressed
        if(txtNombreABuscar.getText().equals("Ingerese el nombre a buscar...")){
            txtNombreABuscar.setText("");
        }
    }//GEN-LAST:event_txtApellidoProfesorMousePressed

    private void txtNombreABuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreABuscarMousePressed
        if(txtNombreABuscar.getText().equals("Ingerese el nombre a buscar...")){
            txtNombreABuscar.setText("");
        }
        txtNombreABuscar.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreABuscarMousePressed

    private void txtNombreABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreABuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreABuscarActionPerformed

    private void txtNombreProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreProfesorMousePressed

    }//GEN-LAST:event_txtNombreProfesorMousePressed

    private void txtNombreProfesorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProfesorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfesorKeyReleased

    private void txtCorreoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoProfesorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoProfesorMousePressed

    private void txtDniProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDniProfesorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniProfesorMousePressed

    private void btnBuscarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseClicked
        if(txtNombreABuscar.getText().equals("")||txtNombreABuscar.getText().equals("Ingerese el nombre a buscar...")){
            JOptionPane.showMessageDialog(this,"No ha digitado ni un nombre para hacer la busqueda");
            txtNombreProfesor.setFocusable(true);
            txtCodigoProfesor.setText("Se mostrara el codigo aqui...");
            txtNombreProfesor.setText("Se mostrara el nombre aqui...");
            txtApellidoProfesor.setText("Se mostrara el apellido aqui...");
            txtTelefonoProfesor.setText("Se mostrara el telefono aqui...");
            txtCorreoProfesor.setText("Se mostrara el correo aqui...");
            txtDniProfesor.setText("Se mostrara el dni aqui...");
            txtCursoProfesor.setText("Se mostrara el curso aqui...");
        }else if(repo.buscarPorNombreProfesor(txtNombreABuscar.getText())==null){
            JOptionPane.showMessageDialog(this,"El nombre digitado no existe");
            txtNombreProfesor.setFocusable(true);
            txtCodigoProfesor.setText("Se mostrara el codigo aqui...");
            txtNombreProfesor.setText("Se mostrara el nombre aqui...");
            txtApellidoProfesor.setText("Se mostrara el apellido aqui...");
            txtTelefonoProfesor.setText("Se mostrara el telefono aqui...");
            txtCorreoProfesor.setText("Se mostrara el correo aqui...");
            txtDniProfesor.setText("Se mostrara el dni aqui...");
            txtCursoProfesor.setText("Se mostrara el curso aqui...");
        }else{
            String nombres = txtNombreABuscar.getText();
            Profesor profeBuscado = repo.buscarPorNombreProfesor(nombres);
            //List<Alumno> alumnoBuscado = text.buscarAlumno(cod);

            int codigo = profeBuscado.getCodProfesor();
            String nombre = profeBuscado.getNameProfesor();
            String apellido = profeBuscado.getApellidoProfesor();
            String telefono = profeBuscado.getTelefonoProfesor();
            String correo = profeBuscado.getCorreoProfesor();
            String dni = profeBuscado.getDniProfesor();
            String curso = repo.obtenerCurso(profeBuscado);

            txtCodigoProfesor.setDisabledTextColor(Color.BLACK);       
            txtNombreProfesor.setDisabledTextColor(Color.BLACK);
            txtApellidoProfesor.setDisabledTextColor(Color.BLACK);
            txtTelefonoProfesor.setDisabledTextColor(Color.BLACK);
            txtCorreoProfesor.setDisabledTextColor(Color.BLACK);
            txtDniProfesor.setDisabledTextColor(Color.BLACK);
            txtCursoProfesor.setDisabledTextColor(Color.BLACK);

            txtCodigoProfesor.setText(Integer.toString(codigo));
            txtNombreProfesor.setText(nombre);
            txtApellidoProfesor.setText(apellido);
            txtTelefonoProfesor.setText(telefono);
            txtCorreoProfesor.setText(correo);
            txtDniProfesor.setText(dni);
            txtCursoProfesor.setText(curso); 
        }
    }//GEN-LAST:event_btnBuscarAlumnoMouseClicked

    private void btnBuscarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseEntered
        pnlBuscarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarAlumnoMouseEntered

    private void btnBuscarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseExited
        pnlBuscarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarAlumnoMouseExited

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        FormInicioAdministrador inicio = new FormInicioAdministrador();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtCodigoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProfesorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProfesorMousePressed

    private void txtTelefonoProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoProfesorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProfesorMousePressed

    private void cmbNombreAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNombreAlumnoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if(cmbNombreAlumno.getSelectedIndex()!=0){
                txtNombreABuscar.setText((String)cmbNombreAlumno.getSelectedItem());
                txtNombreABuscar.setForeground(Color.black);
                cmbNombreAlumno.removeAllItems();
            }
        }
    }//GEN-LAST:event_cmbNombreAlumnoItemStateChanged

    private void txtNombreABuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreABuscarKeyReleased
        busarYPonerComboNombreAlumno();
    }//GEN-LAST:event_txtNombreABuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuscarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualizarAlumno;
    private javax.swing.JLabel apellidoProfesor;
    private javax.swing.JLabel btnBuscarAlumno;
    private javax.swing.JComboBox<String> cmbNombreAlumno;
    private javax.swing.JLabel codigoProfesor;
    private javax.swing.JLabel correoProfesor;
    private javax.swing.JLabel cursoProfesor;
    private javax.swing.JLabel dniProfesor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nombreABuscar;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JPanel pnlBuscarAlumno;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel telefonoProfesor;
    private javax.swing.JTextField txtApellidoProfesor;
    private javax.swing.JTextField txtCodigoProfesor;
    private javax.swing.JTextField txtCorreoProfesor;
    private javax.swing.JTextField txtCursoProfesor;
    private javax.swing.JTextField txtDniProfesor;
    private javax.swing.JTextField txtNombreABuscar;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JTextField txtTelefonoProfesor;
    // End of variables declaration//GEN-END:variables
    void txtDiseno(){
        Border disabledBorder = BorderFactory.createLineBorder(Color.white);
        txtCodigoProfesor.setBorder(disabledBorder);
        txtCodigoProfesor.setDisabledTextColor(Color.GRAY);       
        txtNombreProfesor.setBorder(disabledBorder);
        txtNombreProfesor.setDisabledTextColor(Color.GRAY);
        txtApellidoProfesor.setBorder(disabledBorder);
        txtApellidoProfesor.setDisabledTextColor(Color.GRAY);
        txtTelefonoProfesor.setBorder(disabledBorder);
        txtTelefonoProfesor.setDisabledTextColor(Color.GRAY);        
        txtCorreoProfesor.setBorder(disabledBorder);
        txtCorreoProfesor.setDisabledTextColor(Color.GRAY);
        txtDniProfesor.setBorder(disabledBorder);
        txtDniProfesor.setDisabledTextColor(Color.GRAY);
        txtCursoProfesor.setBorder(disabledBorder);
        txtCursoProfesor.setDisabledTextColor(Color.GRAY);        
    }
    
    private void busarYPonerComboNombreAlumno(){
        cmbNombreAlumno.removeAllItems();
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Profesor x:repo.listarProfesor()){
            if(x.getNameProfesor().toLowerCase().contains(txtNombreABuscar.getText().toLowerCase())&&!x.getNameProfesor().toLowerCase().contains("dministracion")){          
                cmbNombreAlumno.addItem(x.getNameProfesor());
            }
        }
    } 
    
    private void llenarComboBoxs(){
        cmbNombreAlumno.addItem("Elija un nombre...");
        for(Profesor x:repo.listarProfesor()){
            if(x.getEstadoProfesor()==1&&!x.getNameProfesor().toLowerCase().contains("dministracion")){
                cmbNombreAlumno.addItem(x.getNameProfesor());
            }            
        }            
    }    
}
