/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;

/**
 *
 * @author User
 */
public class FormInicioProfesor extends javax.swing.JFrame {

    /**
     * Creates new form FormInicioProfesor
     */
    int xMouse,yMouse;
    RepositorioMySQL repo = new RepositorioMySQL();     
    FormLogueo logueo = new FormLogueo();
    public FormInicioProfesor() {
        initComponents();
        lblSaludoProfesor.setText("Bienvenido profesor@ " + logueo.profesor.getNameProfesor().toUpperCase() + " " +logueo.profesor.getApellidoProfesor().toUpperCase()+"!!!");
        this.setLocationRelativeTo(null);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSaludoProfesor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        pnlRegresar = new javax.swing.JPanel();
        txtRegresar = new javax.swing.JLabel();
        pnlBuscarAlumno = new javax.swing.JPanel();
        btnBuscarAlumno = new javax.swing.JLabel();
        txtBuscarAlumno = new javax.swing.JLabel();
        imagenAlumno = new javax.swing.JLabel();
        txtListarAlumno = new javax.swing.JLabel();
        pnlListarAlumno = new javax.swing.JPanel();
        btnListarAlumno = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        imagenProfesor = new javax.swing.JLabel();
        imagenProfesor1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        pnlActualizarProfesor = new javax.swing.JPanel();
        btnActualizarProfesor = new javax.swing.JLabel();
        txtActualizarProfesor = new javax.swing.JLabel();
        pnlActualizarObservacion = new javax.swing.JPanel();
        btnActualizarObservacion = new javax.swing.JLabel();
        txtAgregarObservacion1 = new javax.swing.JLabel();
        pnlAgregarObservacion = new javax.swing.JPanel();
        btnAgregarObservacion = new javax.swing.JLabel();
        txtAgregarObservacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaludoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        lblSaludoProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludoProfesor.setText("(NOMBRE COMPLETO DEL PROFESOR)");
        jPanel1.add(lblSaludoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("X");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlRegresar.setBackground(new java.awt.Color(255, 255, 255));

        txtRegresar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegresar.setText("<-");
        txtRegresar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRegresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlRegresarLayout = new javax.swing.GroupLayout(pnlRegresar);
        pnlRegresar.setLayout(pnlRegresarLayout);
        pnlRegresarLayout.setHorizontalGroup(
            pnlRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRegresarLayout.setVerticalGroup(
            pnlRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(pnlRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1000, Short.MAX_VALUE)
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        pnlBuscarAlumno.setBackground(new java.awt.Color(254, 199, 7));
        pnlBuscarAlumno.setToolTipText("");

        btnBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnBuscarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAlumnoLayout = new javax.swing.GroupLayout(pnlBuscarAlumno);
        pnlBuscarAlumno.setLayout(pnlBuscarAlumnoLayout);
        pnlBuscarAlumnoLayout.setHorizontalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlBuscarAlumnoLayout.setVerticalGroup(
            pnlBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 150, 40));

        txtBuscarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtBuscarAlumno.setText("Buscar Alumno");
        jPanel1.add(txtBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        imagenAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioImagen1.jpg"))); // NOI18N
        jPanel1.add(imagenAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, 170));

        txtListarAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtListarAlumno.setText("Listar Alumno");
        jPanel1.add(txtListarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        pnlListarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnListarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnListarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListarAlumno.setText("LISTAR");
        btnListarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlListarAlumnoLayout = new javax.swing.GroupLayout(pnlListarAlumno);
        pnlListarAlumno.setLayout(pnlListarAlumnoLayout);
        pnlListarAlumnoLayout.setHorizontalGroup(
            pnlListarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlListarAlumnoLayout.setVerticalGroup(
            pnlListarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnListarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlListarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 150, 40));

        jPanel7.setBackground(new java.awt.Color(254, 199, 7));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 3, 600));

        imagenProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioImagen2.jpg"))); // NOI18N
        jPanel1.add(imagenProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 170, 170));

        imagenProfesor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioImagen3.jpg"))); // NOI18N
        jPanel1.add(imagenProfesor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 150, 150));

        jPanel8.setBackground(new java.awt.Color(254, 199, 7));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 3, 600));

        pnlActualizarProfesor.setBackground(new java.awt.Color(254, 199, 7));

        btnActualizarProfesor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnActualizarProfesor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarProfesor.setText("ACTUALIZAR");
        btnActualizarProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarProfesorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarProfesorLayout = new javax.swing.GroupLayout(pnlActualizarProfesor);
        pnlActualizarProfesor.setLayout(pnlActualizarProfesorLayout);
        pnlActualizarProfesorLayout.setHorizontalGroup(
            pnlActualizarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlActualizarProfesorLayout.setVerticalGroup(
            pnlActualizarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 150, 40));

        txtActualizarProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtActualizarProfesor.setText("Actualizar Cuenta");
        jPanel1.add(txtActualizarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        pnlActualizarObservacion.setBackground(new java.awt.Color(254, 199, 7));
        pnlActualizarObservacion.setToolTipText("");

        btnActualizarObservacion.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnActualizarObservacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarObservacion.setText("ACTUALIZAR");
        btnActualizarObservacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarObservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarObservacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarObservacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarObservacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarObservacionLayout = new javax.swing.GroupLayout(pnlActualizarObservacion);
        pnlActualizarObservacion.setLayout(pnlActualizarObservacionLayout);
        pnlActualizarObservacionLayout.setHorizontalGroup(
            pnlActualizarObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlActualizarObservacionLayout.setVerticalGroup(
            pnlActualizarObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 150, 40));

        txtAgregarObservacion1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtAgregarObservacion1.setText("Actualizar Observacion");
        jPanel1.add(txtAgregarObservacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));

        pnlAgregarObservacion.setBackground(new java.awt.Color(254, 199, 7));
        pnlAgregarObservacion.setToolTipText("");

        btnAgregarObservacion.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnAgregarObservacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregarObservacion.setText("AGREGAR");
        btnAgregarObservacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarObservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarObservacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarObservacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarObservacionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarObservacionLayout = new javax.swing.GroupLayout(pnlAgregarObservacion);
        pnlAgregarObservacion.setLayout(pnlAgregarObservacionLayout);
        pnlAgregarObservacionLayout.setHorizontalGroup(
            pnlAgregarObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pnlAgregarObservacionLayout.setVerticalGroup(
            pnlAgregarObservacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregarObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlAgregarObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 150, 40));

        txtAgregarObservacion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 15)); // NOI18N
        txtAgregarObservacion.setText("Agregar Observacion");
        jPanel1.add(txtAgregarObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPredeAlumno.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnBuscarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseClicked
        FormBuscarAlumno buscar = new FormBuscarAlumno();
        buscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBuscarAlumnoMouseClicked

    private void btnBuscarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseEntered
        pnlBuscarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnBuscarAlumnoMouseEntered

    private void btnBuscarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoMouseExited
        pnlBuscarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnBuscarAlumnoMouseExited

    private void btnListarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarAlumnoMouseClicked
        FormListarAlumnoDesdeProfesor list = new FormListarAlumnoDesdeProfesor();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarAlumnoMouseClicked

    private void btnListarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarAlumnoMouseEntered
        pnlListarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnListarAlumnoMouseEntered

    private void btnListarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarAlumnoMouseExited
        pnlListarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnListarAlumnoMouseExited

    private void btnActualizarProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarProfesorMouseClicked
        FormActualizarCuentaProfesor actu = new FormActualizarCuentaProfesor();
        actu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnActualizarProfesorMouseClicked

    private void btnActualizarProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarProfesorMouseEntered
        pnlActualizarProfesor.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarProfesorMouseEntered

    private void btnActualizarProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarProfesorMouseExited
        pnlActualizarProfesor.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarProfesorMouseExited

    private void btnAgregarObservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarObservacionMouseClicked
        FormAgregarObservacion agregar = new FormAgregarObservacion();
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarObservacionMouseClicked

    private void btnAgregarObservacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarObservacionMouseEntered
        pnlAgregarObservacion.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnAgregarObservacionMouseEntered

    private void btnAgregarObservacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarObservacionMouseExited
        pnlAgregarObservacion.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnAgregarObservacionMouseExited

    private void txtRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegresarMouseClicked
        FormLogueo list = new FormLogueo();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtRegresarMouseClicked

    private void txtRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegresarMouseEntered
        pnlRegresar.setBackground(new Color(254,199,7));
        txtRegresar.setForeground(Color.white);
    }//GEN-LAST:event_txtRegresarMouseEntered

    private void txtRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegresarMouseExited
        pnlRegresar.setBackground(Color.white);
        txtRegresar.setForeground(Color.black);
    }//GEN-LAST:event_txtRegresarMouseExited

    private void btnActualizarObservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarObservacionMouseClicked
        FormActualizarObservacion agregar = new FormActualizarObservacion();
        agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnActualizarObservacionMouseClicked

    private void btnActualizarObservacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarObservacionMouseEntered
        pnlActualizarObservacion.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarObservacionMouseEntered

    private void btnActualizarObservacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarObservacionMouseExited
        pnlActualizarObservacion.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarObservacionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicioProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualizarObservacion;
    private javax.swing.JLabel btnActualizarProfesor;
    private javax.swing.JLabel btnAgregarObservacion;
    private javax.swing.JLabel btnBuscarAlumno;
    private javax.swing.JLabel btnListarAlumno;
    private javax.swing.JLabel imagenAlumno;
    private javax.swing.JLabel imagenProfesor;
    private javax.swing.JLabel imagenProfesor1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblSaludoProfesor;
    private javax.swing.JPanel pnlActualizarObservacion;
    private javax.swing.JPanel pnlActualizarProfesor;
    private javax.swing.JPanel pnlAgregarObservacion;
    private javax.swing.JPanel pnlBuscarAlumno;
    private javax.swing.JPanel pnlListarAlumno;
    private javax.swing.JPanel pnlRegresar;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JLabel txtActualizarProfesor;
    private javax.swing.JLabel txtAgregarObservacion;
    private javax.swing.JLabel txtAgregarObservacion1;
    private javax.swing.JLabel txtBuscarAlumno;
    private javax.swing.JLabel txtListarAlumno;
    private javax.swing.JLabel txtRegresar;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
