/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author User
 */
public class FormActualizarCuentaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form FormActualizarCuentaProfesor
     */
    int xMouse,yMouse; // Creamos variables int que referenciaran al mouse
    RepositorioMySQL repo = new RepositorioMySQL(); // Instanciamos a la clase RepositorioSQL para todos los metodos
    FormLogueo logueo = new FormLogueo(); // Instanciamos a la clase formulaio FormLogueo para los datos que necesitaremos
    public FormActualizarCuentaProfesor() {
        initComponents();
        // Con esto ponemos el diseño predeterminado que tendra nuestro programa y con la otra funcion llenamos los comboBoxs
        llenarDatos();
        txtDiseno();
        this.setLocationRelativeTo(null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        apellidoNuevoProfesor2 = new javax.swing.JLabel();
        txtRepetirPasswordNuevo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        nombreProfesor = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        apellidoProfesor = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtCodigoCuenta = new javax.swing.JTextField();
        codigoCuenta = new javax.swing.JLabel();
        txtPasswordNuevo = new javax.swing.JTextField();
        txtUsuarioNuevo = new javax.swing.JTextField();
        nombreNuevoProfesor = new javax.swing.JLabel();
        apellidoNuevoProfesor = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        pnlActualizarAlumno = new javax.swing.JPanel();
        btnActualizarAlumno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidoNuevoProfesor1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        pnlSalir.setBackground(new java.awt.Color(255, 255, 255));

        txtSalir.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        txtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalir.setText("VOLVER");
        txtSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSalirLayout = new javax.swing.GroupLayout(pnlSalir);
        pnlSalir.setLayout(pnlSalirLayout);
        pnlSalirLayout.setHorizontalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSalirLayout.setVerticalGroup(
            pnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Requisitos de contraseña:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("- Longitud mínima de 8 caracteres ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("- Al menos una letras minúscula ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("- Al menos un numero ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("- Al menos una letra mayúscula ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("- Al menos un caracter especial");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText(" (por ejemplo, @, #, $, etc.)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 220, 190));

        apellidoNuevoProfesor2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoNuevoProfesor2.setText("Repetir Password Nuevo");
        jPanel1.add(apellidoNuevoProfesor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        txtRepetirPasswordNuevo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtRepetirPasswordNuevo.setForeground(new java.awt.Color(102, 102, 102));
        txtRepetirPasswordNuevo.setText("Repetir su contrasenia nueva...");
        txtRepetirPasswordNuevo.setToolTipText("");
        txtRepetirPasswordNuevo.setBorder(null);
        txtRepetirPasswordNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRepetirPasswordNuevoMousePressed(evt);
            }
        });
        txtRepetirPasswordNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepetirPasswordNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRepetirPasswordNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 350, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 350, 10));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel3.setText("ACTUALIZAR CUENTA DE INICIO DE SESION  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Se mostrara el nombre aqui...");
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(null);
        txtUsuario.setEnabled(false);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 350, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 350, 10));

        nombreProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreProfesor.setText("Usuario");
        jPanel1.add(nombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 350, 10));

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("Se mostrara el apellido aqui...");
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        txtPassword.setEnabled(false);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 350, 30));

        apellidoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoProfesor.setText("Password");
        jPanel1.add(apellidoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 350, 10));

        txtCodigoCuenta.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtCodigoCuenta.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoCuenta.setText("Se mostrara el codigo aqui...");
        txtCodigoCuenta.setToolTipText("");
        txtCodigoCuenta.setBorder(null);
        txtCodigoCuenta.setEnabled(false);
        jPanel1.add(txtCodigoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 350, 30));

        codigoCuenta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        codigoCuenta.setText("Codigo de Cuenta");
        jPanel1.add(codigoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtPasswordNuevo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPasswordNuevo.setForeground(new java.awt.Color(102, 102, 102));
        txtPasswordNuevo.setText("Ingrese su contrasenia nueva...");
        txtPasswordNuevo.setToolTipText("");
        txtPasswordNuevo.setBorder(null);
        txtPasswordNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordNuevoMousePressed(evt);
            }
        });
        jPanel1.add(txtPasswordNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 350, 30));

        txtUsuarioNuevo.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtUsuarioNuevo.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuarioNuevo.setToolTipText("");
        txtUsuarioNuevo.setBorder(null);
        txtUsuarioNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioNuevoMousePressed(evt);
            }
        });
        txtUsuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 350, 30));

        nombreNuevoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        nombreNuevoProfesor.setText("Usuario Nuevo");
        jPanel1.add(nombreNuevoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        apellidoNuevoProfesor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoNuevoProfesor.setText("Password Nuevo");
        jPanel1.add(apellidoNuevoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 350, 10));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 350, 10));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
        jLabel2.setText("DATOS NUEVOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        pnlActualizarAlumno.setBackground(new java.awt.Color(254, 199, 7));

        btnActualizarAlumno.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        btnActualizarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizarAlumno.setText("ACTUALIZAR");
        btnActualizarAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarAlumnoLayout = new javax.swing.GroupLayout(pnlActualizarAlumno);
        pnlActualizarAlumno.setLayout(pnlActualizarAlumnoLayout);
        pnlActualizarAlumnoLayout.setHorizontalGroup(
            pnlActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlActualizarAlumnoLayout.setVerticalGroup(
            pnlActualizarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlActualizarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoActualizarProfesor.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 710));

        apellidoNuevoProfesor1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        apellidoNuevoProfesor1.setText("Password Nuevo");
        jPanel1.add(apellidoNuevoProfesor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 350, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        // Volvemos al FormInicioProfesor
        FormInicioProfesor inicio = new FormInicioProfesor();
        inicio.setVisible(true);
        dispose();            
        
    }//GEN-LAST:event_txtSalirMouseClicked

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        // Creamos un evento cuando el mouse entra para que cambie de color y del texto
        pnlSalir.setBackground(new Color(254,199,7));
        txtSalir.setForeground(Color.white);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        // Creamos un evento cuando el mouse sale para que se restaure el color y del texto
        pnlSalir.setBackground(Color.white);
        txtSalir.setForeground(Color.black);
    }//GEN-LAST:event_txtSalirMouseExited

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // Creamos un evento en el cual se ejecuta cuando arrastramos el programa
        // Se obtienen las coordenadas actuales del ratón en la pantalla del programa
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // Se mueve el componente JPanel arrastrándolo según las diferencias de coordenadas
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // Se capturan las coordenadas del ratón cuando se presiona
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void txtPasswordNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordNuevoMousePressed
        // Creamos un metodo en el cual se ejecuta cuando presionamos en el cuadro de texto
        // Evaluamos el txt selecionado y ponemos el texto predeterminado si el usuario no pone nada
        if(txtPasswordNuevo.getText().equals("Ingrese su contrasenia nueva...")){
            txtPasswordNuevo.setText("");
        }
        txtPasswordNuevo.setForeground(Color.black);
        // Evaluamos los demas txts y si no hay nada se pone el texto predeterminado
        if(txtUsuarioNuevo.getText().equals("")){
            txtUsuarioNuevo.setText("Ingrese su usuario nuevo...");
            txtUsuarioNuevo.setForeground(Color.gray);
        }
        if(txtRepetirPasswordNuevo.getText().equals("")){
            txtRepetirPasswordNuevo.setText("Repetir su contrasenia nueva...");
            txtRepetirPasswordNuevo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPasswordNuevoMousePressed

    private void txtUsuarioNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioNuevoMousePressed
        // Creamos un metodo en el cual se ejecuta cuando presionamos en el cuadro de texto
        // Evaluamos el txt selecionado y ponemos el texto predeterminado si el usuario no pone nada
        if(txtUsuarioNuevo.getText().equals("Ingrese su usuario nuevo...")){
            txtUsuarioNuevo.setText("");
        }
        txtUsuarioNuevo.setForeground(Color.black);
        // Evaluamos los demas txts y si no hay nada se pone el texto predeterminado
        if(txtPasswordNuevo.getText().equals("")){
            txtPasswordNuevo.setText("Ingrese su contrasenia nueva...");
            txtPasswordNuevo.setForeground(Color.gray);
        }
        if(txtRepetirPasswordNuevo.getText().equals("")){
            txtRepetirPasswordNuevo.setText("Repetir su contrasenia nueva...");
            txtRepetirPasswordNuevo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioNuevoMousePressed

    private void btnActualizarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseClicked
        // Creamos un evento en el cual se ejecuta cuando hacemos click en el boton
        // Ponemos una condicional que evalua si hay algun dato faltante
        if(txtUsuarioNuevo.getText().equals("Ingerese su usuario nuevo...")||txtPasswordNuevo.getText().equals("Ingerese su contrasenia nueva...")){
            JOptionPane.showMessageDialog(this,"Hay un dato o varios en blanco\nPor favor completelos");
            txtUsuarioNuevo.setFocusable(true);
        }else{
            // Despues de pasar los filtros se actualizaran los datos de la cuenta del profesor 
            // Se crean las variables que extraeran de los txts que tienen los datos nuevos
            String usuario = txtUsuarioNuevo.getText();
            String password = txtPasswordNuevo.getText();
            String confirmarPassword = txtRepetirPasswordNuevo.getText();

            if(password.equals(confirmarPassword)){
                if(!validarPassword(password)){
                    JOptionPane.showMessageDialog(this, 
                        "La contrasenia no cumple con los requisitos:\n" +
                        "- Mínimo 8 caracteres\n" +
                        "- Al menos una letra mayúscula\n" +
                        "- Al menos una letra minúscula\n" +
                        "- Al menos un número\n" +
                        "- Al menos un carácter especial (@, #, $, etc.)",
                        "Contraseña inválida",
                        JOptionPane.WARNING_MESSAGE);
                    txtPasswordNuevo.requestFocus();
                    return;
                }
                // Creamos un objeto con los datos nuevo y lo mandamos al metodo actualizarUsuario
                Usuario usu = new Usuario(usuario,password,logueo.profesor.getCodProfesor());
                repo.actualizarUsuario(usu);
                // Vaciamos los cuadros de texto y ponemos el diseño predeterminado que escogimos y al final enviamos un mensaje
                vaciarTxt();
                txtDiseno();
                JOptionPane.showMessageDialog(this,"Usuario actualizado correctamente :D");
                txtUsuarioNuevo.setFocusable(true);
            }else{
                JOptionPane.showMessageDialog(this,"La contraseña no coinciden");
                vaciarTxt();
            }
        }
    }//GEN-LAST:event_btnActualizarAlumnoMouseClicked

    private void btnActualizarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseEntered
        // Creamos un evento cuando el mouse entra para que cambie el color del panel
        pnlActualizarAlumno.setBackground(new Color(254,214,75));
    }//GEN-LAST:event_btnActualizarAlumnoMouseEntered

    private void btnActualizarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoMouseExited
        // Creamos un evento cuando el mouse sale para que se restaure el color del panel
        pnlActualizarAlumno.setBackground(new Color(254,199,7));
    }//GEN-LAST:event_btnActualizarAlumnoMouseExited

    private void txtRepetirPasswordNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRepetirPasswordNuevoMousePressed
        // Creamos un metodo en el cual se ejecuta cuando presionamos en el cuadro de texto
        // Evaluamos el txt selecionado y ponemos el texto predeterminado si el usuario no pone nada
        if(txtRepetirPasswordNuevo.getText().equals("Repetir su contrasenia nueva...")){
            txtRepetirPasswordNuevo.setText("");
        }
        txtRepetirPasswordNuevo.setForeground(Color.black);
        // Evaluamos los demas txts y si no hay nada se pone el texto predeterminado
        if(txtUsuarioNuevo.getText().equals("")){
            txtUsuarioNuevo.setText("Ingrese su usuario nuevo...");
            txtUsuarioNuevo.setForeground(Color.gray);
        }
        if(txtPasswordNuevo.getText().equals("")){
            txtPasswordNuevo.setText("Ingrese su contrasenia nueva...");
            txtPasswordNuevo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtRepetirPasswordNuevoMousePressed

    private void txtRepetirPasswordNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepetirPasswordNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepetirPasswordNuevoActionPerformed

    private void txtUsuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormActualizarCuentaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormActualizarCuentaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormActualizarCuentaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormActualizarCuentaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormActualizarCuentaProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoNuevoProfesor;
    private javax.swing.JLabel apellidoNuevoProfesor1;
    private javax.swing.JLabel apellidoNuevoProfesor2;
    private javax.swing.JLabel apellidoProfesor;
    private javax.swing.JLabel btnActualizarAlumno;
    private javax.swing.JLabel codigoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel nombreNuevoProfesor;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JPanel pnlActualizarAlumno;
    private javax.swing.JPanel pnlSalir;
    private javax.swing.JTextField txtCodigoCuenta;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordNuevo;
    private javax.swing.JTextField txtRepetirPasswordNuevo;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioNuevo;
    // End of variables declaration//GEN-END:variables

    // LLenamos los cuadros de texto de los datos de la cuenta del profesor
    private void llenarDatos() {
        Usuario usuario = repo.buscarPorCodigoUsuario(logueo.profesor.getCodProfesor());
        txtCodigoCuenta.setText(Integer.toString(usuario.getCodUsuario()));
        txtUsuario.setText(usuario.getUsuario());
        txtPassword.setText(usuario.getPassword());
    }
    
    // Creamos un funcion en el cual tendra el diseño predeterminado que tendra los txt enabled
    private void txtDiseno(){
        Border disabledBorder = BorderFactory.createLineBorder(Color.white);
        txtCodigoCuenta.setBorder(disabledBorder);
        txtCodigoCuenta.setDisabledTextColor(Color.black);
        txtUsuario.setBorder(disabledBorder);
        txtUsuario.setDisabledTextColor(Color.black);
        txtPassword.setBorder(disabledBorder);
        txtPassword.setDisabledTextColor(Color.black);
    }
    
    // Vaciamos todos los txts con los mensajes predeterminados
    void vaciarTxt(){
        txtUsuarioNuevo.setText(""); 
        txtPasswordNuevo.setText("Ingerese su contrasenia nueva..."); 
        txtRepetirPasswordNuevo.setText("Repita su contrasenia nueva...");
        txtUsuarioNuevo.setFocusable(true);
     }
    
    // Método para validar la contraseña
    private boolean validarPassword(String password) {
        // Verificar longitud mínima
        if(password.length() < 8) {
            return false;
        }

        // Variables para verificar cada requisito
        boolean tieneMayuscula = false;
        boolean tieneMinuscula = false;
        boolean tieneNumero = false;
        boolean tieneEspecial = false;

        // Caracteres especiales permitidos
        String caracteresEspeciales = "@#$%^&+=!*()_-{}[]|:;'<>,.?/~`";

        // Recorrer cada caracter de la contraseña
        for(char c : password.toCharArray()) {
            if(Character.isUpperCase(c)) {
                tieneMayuscula = true;
            } else if(Character.isLowerCase(c)) {
                tieneMinuscula = true;
            } else if(Character.isDigit(c)) {
                tieneNumero = true;
            } else if(caracteresEspeciales.indexOf(c) != -1) {
                tieneEspecial = true;
            }
        }

        // Retornar true solo si cumple todos los requisitos
        return tieneMayuscula && tieneMinuscula && tieneNumero && tieneEspecial;
    }
}
